name: 'Run iOS end to end tests action'
description: 'Runs end to end tests on iOS device'
inputs:
  test_name:
    description: 'Test case/suite name. Will run all tests in the test plan if not provided.'
    required: false
  xcode_test_plan:
    description: 'Xcode Test Plan to run'
    required: true

runs:
  using: 'composite'
  steps:
      # Set up a unique output directory
    - name: Set up outputs directory
      run: |
        if [ -n "$TEST_NAME" ]; then
          # Strip slashes to avoid creating subdirectories
          test_name_sanitized=$(printf "$TEST_NAME" | sed 's/\//_/g')
          echo "TEST_OUTPUT_DIRECTORY=output-$test_name_sanitized" >> $GITHUB_ENV
        else
          echo "TEST_OUTPUT_DIRECTORY=output" >> $GITHUB_ENV
        fi

        echo "Creating output directory ${{ env.TEST_OUTPUT_DIRECTORY }}"
        mkdir "${{ env.TEST_OUTPUT_DIRECTORY }}"
      shell: bash
      env:
        TEST_NAME: ${{ inputs.test_name }}

    - name: Debug print
      run: |
        echo "TEST_OUTPUT_DIRECTORY: $TEST_OUTPUT_DIRECTORY"
        echo "${{ env.TEST_OUTPUT_DIRECTORY }}"
      shell: bash

    - name: Uninstall app
      run: ios-deploy --id $IOS_TEST_DEVICE_UDID --uninstall_only --bundle_id net.mullvad.MullvadVPN
      shell: bash
      env:
        IOS_TEST_DEVICE_UDID: ${{ env.TEST_DEVICE_UDID }}

    - name: Run end-to-end-tests
      run: |
        if [ -n "$TEST_NAME" ]; then
          #TEST_NAME_ARGUMENT=" -only-testing $TEST_NAME"
          TEST_NAME_ARGUMNET=""
        else
          TEST_NAME_ARGUMENT=""
        fi
        set -o pipefail && env NSUnbufferedIO=YES xcodebuild \
          -project MullvadVPN.xcodeproj \
          -scheme MullvadVPNUITests \
          -testPlan $XCODE_TEST_PLAN $TEST_NAME_ARGUMENT \
          -resultBundlePath ${{ env.TEST_OUTPUT_DIRECTORY }}/xcode-test-report \
          -derivedDataPath derived-data \
          -destination "platform=iOS,id=$TEST_DEVICE_UDID" \
          test-without-building 2>&1 #| xcbeautify --report junit --report-path ${{ env.TEST_OUTPUT_DIRECTORY }}/junit-test-report
      shell: bash
      working-directory: ios/
      env:
        TEST_NAME: ${{ inputs.test_name }}
        XCODE_TEST_PLAN: ${{ inputs.xcode_test_plan }}

    - name: Store test report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ios/${{ env.TEST_OUTPUT_DIRECTORY }}/junit-test-report/junit.xml
          ios/${{ env.TEST_OUTPUT_DIRECTORY }}/xcode-test-report.xcresult
      env:
        TEST_NAME: ${{ inputs.test_name }}
