// Auto-generated from relays.json

import Foundation

let relayLocationList: [String: String] = [
    "Australia": NSLocalizedString("Australia", comment: ""),
    "Netherlands": NSLocalizedString("Netherlands", comment: ""),
    "USA": NSLocalizedString("USA", comment: ""),
    "Greece": NSLocalizedString("Greece", comment: ""),
    "New Zealand": NSLocalizedString("New Zealand", comment: ""),
    "Thailand": NSLocalizedString("Thailand", comment: ""),
    "Spain": NSLocalizedString("Spain", comment: ""),
    "Serbia": NSLocalizedString("Serbia", comment: ""),
    "Germany": NSLocalizedString("Germany", comment: ""),
    "Colombia": NSLocalizedString("Colombia", comment: ""),
    "France": NSLocalizedString("France", comment: ""),
    "Slovakia": NSLocalizedString("Slovakia", comment: ""),
    "Belgium": NSLocalizedString("Belgium", comment: ""),
    "Romania": NSLocalizedString("Romania", comment: ""),
    "Hungary": NSLocalizedString("Hungary", comment: ""),
    "Argentina": NSLocalizedString("Argentina", comment: ""),
    "Canada": NSLocalizedString("Canada", comment: ""),
    "Denmark": NSLocalizedString("Denmark", comment: ""),
    "Ireland": NSLocalizedString("Ireland", comment: ""),
    "Brazil": NSLocalizedString("Brazil", comment: ""),
    "UK": NSLocalizedString("UK", comment: ""),
    "Sweden": NSLocalizedString("Sweden", comment: ""),
    "Finland": NSLocalizedString("Finland", comment: ""),
    "Hong Kong": NSLocalizedString("Hong Kong", comment: ""),
    "Turkey": NSLocalizedString("Turkey", comment: ""),
    "Indonesia": NSLocalizedString("Indonesia", comment: ""),
    "South Africa": NSLocalizedString("South Africa", comment: ""),
    "Malaysia": NSLocalizedString("Malaysia", comment: ""),
    "Ukraine": NSLocalizedString("Ukraine", comment: ""),
    "Nigeria": NSLocalizedString("Nigeria", comment: ""),
    "Peru": NSLocalizedString("Peru", comment: ""),
    "Portugal": NSLocalizedString("Portugal", comment: ""),
    "Slovenia": NSLocalizedString("Slovenia", comment: ""),
    "Philippines": NSLocalizedString("Philippines", comment: ""),
    "Italy": NSLocalizedString("Italy", comment: ""),
    "Cyprus": NSLocalizedString("Cyprus", comment: ""),
    "Japan": NSLocalizedString("Japan", comment: ""),
    "Norway": NSLocalizedString("Norway", comment: ""),
    "Czech Republic": NSLocalizedString("Czech Republic", comment: ""),
    "Mexico": NSLocalizedString("Mexico", comment: ""),
    "Chile": NSLocalizedString("Chile", comment: ""),
    "Singapore": NSLocalizedString("Singapore", comment: ""),
    "Bulgaria": NSLocalizedString("Bulgaria", comment: ""),
    "Estonia": NSLocalizedString("Estonia", comment: ""),
    "Israel": NSLocalizedString("Israel", comment: ""),
    "Albania": NSLocalizedString("Albania", comment: ""),
    "Austria": NSLocalizedString("Austria", comment: ""),
    "Poland": NSLocalizedString("Poland", comment: ""),
    "Croatia": NSLocalizedString("Croatia", comment: ""),
    "Switzerland": NSLocalizedString("Switzerland", comment: ""),
    "Adelaide": NSLocalizedString("Adelaide", comment: ""),
    "Amsterdam": NSLocalizedString("Amsterdam", comment: ""),
    "Ashburn, VA": NSLocalizedString("Ashburn, VA", comment: ""),
    "Athens": NSLocalizedString("Athens", comment: ""),
    "Atlanta, GA": NSLocalizedString("Atlanta, GA", comment: ""),
    "Auckland": NSLocalizedString("Auckland", comment: ""),
    "Bangkok": NSLocalizedString("Bangkok", comment: ""),
    "Barcelona": NSLocalizedString("Barcelona", comment: ""),
    "Belgrade": NSLocalizedString("Belgrade", comment: ""),
    "Berlin": NSLocalizedString("Berlin", comment: ""),
    "Bogota": NSLocalizedString("Bogota", comment: ""),
    "Bordeaux": NSLocalizedString("Bordeaux", comment: ""),
    "Boston, MA": NSLocalizedString("Boston, MA", comment: ""),
    "Bratislava": NSLocalizedString("Bratislava", comment: ""),
    "Brisbane": NSLocalizedString("Brisbane", comment: ""),
    "Brussels": NSLocalizedString("Brussels", comment: ""),
    "Bucharest": NSLocalizedString("Bucharest", comment: ""),
    "Budapest": NSLocalizedString("Budapest", comment: ""),
    "Buenos Aires": NSLocalizedString("Buenos Aires", comment: ""),
    "Calgary": NSLocalizedString("Calgary", comment: ""),
    "Chicago, IL": NSLocalizedString("Chicago, IL", comment: ""),
    "Copenhagen": NSLocalizedString("Copenhagen", comment: ""),
    "Dallas, TX": NSLocalizedString("Dallas, TX", comment: ""),
    "Denver, CO": NSLocalizedString("Denver, CO", comment: ""),
    "Detroit, MI": NSLocalizedString("Detroit, MI", comment: ""),
    "Dublin": NSLocalizedString("Dublin", comment: ""),
    "Dusseldorf": NSLocalizedString("Dusseldorf", comment: ""),
    "Fortaleza": NSLocalizedString("Fortaleza", comment: ""),
    "Frankfurt": NSLocalizedString("Frankfurt", comment: ""),
    "Glasgow": NSLocalizedString("Glasgow", comment: ""),
    "Gothenburg": NSLocalizedString("Gothenburg", comment: ""),
    "Helsinki": NSLocalizedString("Helsinki", comment: ""),
    "Houston, TX": NSLocalizedString("Houston, TX", comment: ""),
    "Istanbul": NSLocalizedString("Istanbul", comment: ""),
    "Jakarta": NSLocalizedString("Jakarta", comment: ""),
    "Johannesburg": NSLocalizedString("Johannesburg", comment: ""),
    "Kansas City, MO": NSLocalizedString("Kansas City, MO", comment: ""),
    "Kuala Lumpur": NSLocalizedString("Kuala Lumpur", comment: ""),
    "Kyiv": NSLocalizedString("Kyiv", comment: ""),
    "Lagos": NSLocalizedString("Lagos", comment: ""),
    "Lima": NSLocalizedString("Lima", comment: ""),
    "Lisbon": NSLocalizedString("Lisbon", comment: ""),
    "Ljubljana": NSLocalizedString("Ljubljana", comment: ""),
    "London": NSLocalizedString("London", comment: ""),
    "Los Angeles, CA": NSLocalizedString("Los Angeles, CA", comment: ""),
    "Madrid": NSLocalizedString("Madrid", comment: ""),
    "Malmö": NSLocalizedString("Malmö", comment: ""),
    "Manchester": NSLocalizedString("Manchester", comment: ""),
    "Manila": NSLocalizedString("Manila", comment: ""),
    "Marseille": NSLocalizedString("Marseille", comment: ""),
    "McAllen, TX": NSLocalizedString("McAllen, TX", comment: ""),
    "Melbourne": NSLocalizedString("Melbourne", comment: ""),
    "Miami, FL": NSLocalizedString("Miami, FL", comment: ""),
    "Milan": NSLocalizedString("Milan", comment: ""),
    "Montreal": NSLocalizedString("Montreal", comment: ""),
    "New York, NY": NSLocalizedString("New York, NY", comment: ""),
    "Nicosia": NSLocalizedString("Nicosia", comment: ""),
    "Osaka": NSLocalizedString("Osaka", comment: ""),
    "Oslo": NSLocalizedString("Oslo", comment: ""),
    "Palermo": NSLocalizedString("Palermo", comment: ""),
    "Paris": NSLocalizedString("Paris", comment: ""),
    "Perth": NSLocalizedString("Perth", comment: ""),
    "Phoenix, AZ": NSLocalizedString("Phoenix, AZ", comment: ""),
    "Prague": NSLocalizedString("Prague", comment: ""),
    "Queretaro": NSLocalizedString("Queretaro", comment: ""),
    "Raleigh, NC": NSLocalizedString("Raleigh, NC", comment: ""),
    "Salt Lake City, UT": NSLocalizedString("Salt Lake City, UT", comment: ""),
    "San Jose, CA": NSLocalizedString("San Jose, CA", comment: ""),
    "Santiago": NSLocalizedString("Santiago", comment: ""),
    "Sao Paulo": NSLocalizedString("Sao Paulo", comment: ""),
    "Seattle, WA": NSLocalizedString("Seattle, WA", comment: ""),
    "Secaucus, NJ": NSLocalizedString("Secaucus, NJ", comment: ""),
    "Sofia": NSLocalizedString("Sofia", comment: ""),
    "Stavanger": NSLocalizedString("Stavanger", comment: ""),
    "Stockholm": NSLocalizedString("Stockholm", comment: ""),
    "Sydney": NSLocalizedString("Sydney", comment: ""),
    "Tallinn": NSLocalizedString("Tallinn", comment: ""),
    "Tel Aviv": NSLocalizedString("Tel Aviv", comment: ""),
    "Tirana": NSLocalizedString("Tirana", comment: ""),
    "Tokyo": NSLocalizedString("Tokyo", comment: ""),
    "Toronto": NSLocalizedString("Toronto", comment: ""),
    "Valencia": NSLocalizedString("Valencia", comment: ""),
    "Vancouver": NSLocalizedString("Vancouver", comment: ""),
    "Vienna": NSLocalizedString("Vienna", comment: ""),
    "Warsaw": NSLocalizedString("Warsaw", comment: ""),
    "Washington DC": NSLocalizedString("Washington DC", comment: ""),
    "Zagreb": NSLocalizedString("Zagreb", comment: ""),
    "Zurich": NSLocalizedString("Zurich", comment: ""),
]
