#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/../.." && pwd )"
REPORTS_DIR="$REPO_ROOT/android/app/build/reports"
JNI_DIR="$REPO_ROOT/mullvad-jni"
DIST_DIR="$REPO_ROOT/dist"
CARGO_TARGETS=(aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android)
VERSION="$(cargo run -q --manifest-path "$REPO_ROOT/Cargo.toml" --bin mullvad-version versionName)"
SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(git -C "$REPO_ROOT" log -1 --format=%ct)}"

export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

function main {
    trap cleanup EXIT

    generate_android_sboms
    generate_cargo_sboms

    merge_sboms ossProdRelease apk
    merge_sboms playProdRelease play.apk

    strip_sboms
    timestamp_sboms
    verify_sboms
}

function generate_android_sboms {
    "$REPO_ROOT/android/gradlew" -p "$REPO_ROOT/android" --console plain \
        generateOssProdReleaseSbom generatePlayProdReleaseSbom
}

function generate_cargo_sboms {
    local target
    for target in "${CARGO_TARGETS[@]}"; do
        cargo cyclonedx --format json --spec-version 1.5 \
            --target "$target" --target-in-filename \
            --manifest-path "$JNI_DIR/Cargo.toml"
    done
}

function merge_sboms {
    local variant=$1
    local artifact=$2
    local sbom="$DIST_DIR/MullvadVPN-$VERSION.$artifact.cdx.json"

    mkdir -p "$DIST_DIR"
    cyclonedx merge \
        --input-files "$REPORTS_DIR/$variant.jvm.cdx.json" "$JNI_DIR"/mullvad-jni_*.cdx.json \
        --input-format json --output-format json --output-version v1_5 \
        --name mullvad-vpn-android --version "$VERSION" \
        --output-file "$sbom"
}

function strip_sboms {
    # Local crate IDs hold the URL-encoded checkout path, e.g. path+file:///build/mullvad-jni#0.0.0
    local jni_id checkout_id
    jni_id="$(cargo pkgid --manifest-path "$JNI_DIR/Cargo.toml")"
    checkout_id="$(dirname "$jni_id")"

    local sbom
    for sbom in "$DIST_DIR/MullvadVPN-$VERSION".*.cdx.json; do
        jq --arg checkout_id "$checkout_id/" '
            # Random UUID generated by every merge
            del(.serialNumber)

            # Make local crate IDs relative to the checkout
            | (.. | strings) |= (split($checkout_id) | join("path+file://./"))

            # Crates with target-specific dependencies get one entry per target, so combine them
            | .dependencies |= (
                group_by(.ref)
                | map({ref: .[0].ref, dependsOn: (map(.dependsOn[]?) | unique)})
            )' \
            "$sbom" > "$sbom.tmp"
        mv "$sbom.tmp" "$sbom"
    done
}

function timestamp_sboms {
    local sbom
    for sbom in "$DIST_DIR/MullvadVPN-$VERSION".*.cdx.json; do
        jq --argjson epoch "$SOURCE_DATE_EPOCH" '.metadata.timestamp = ($epoch | todate)' \
            "$sbom" > "$sbom.tmp"
        mv "$sbom.tmp" "$sbom"
    done
}

function verify_sboms {
    local sbom
    for sbom in "$DIST_DIR/MullvadVPN-$VERSION".*.cdx.json; do
        cyclonedx validate --input-file "$sbom" --input-format json --input-version v1_5 \
            --fail-on-errors
    done
}

function cleanup {
    find "$REPO_ROOT" -name '*_*-linux-android*.cdx.json' -delete
}

main
