import { DeprecatedColorTokens } from '../tokens';

export const deprecatedColors = {
  '--color-darker-blue': DeprecatedColorTokens.darkerBlue,
  '--color-dark-blue': DeprecatedColorTokens.darkBlue,
  '--color-blue': DeprecatedColorTokens.blue,
  '--color-dark-green': DeprecatedColorTokens.darkGreen,
  '--color-green': DeprecatedColorTokens.green,
  '--color-red': DeprecatedColorTokens.red,
  '--color-darkYellow': DeprecatedColorTokens.darkYellow,
  '--color-yellow': DeprecatedColorTokens.yellow,
  '--color-black': DeprecatedColorTokens.black,
  '--color-white': DeprecatedColorTokens.white,
  '--color-white-90': DeprecatedColorTokens.white90,
  '--color-white-80': DeprecatedColorTokens.white80,
  '--color-white-60': DeprecatedColorTokens.white60,
  '--color-white-50': DeprecatedColorTokens.white50,
  '--color-white-40': DeprecatedColorTokens.white40,
  '--color-white-20': DeprecatedColorTokens.white20,
  '--color-white-10': DeprecatedColorTokens.white10,
  '--color-blue10': DeprecatedColorTokens.blue10,
  '--color-blue-20': DeprecatedColorTokens.blue20,
  '--color-blue-40': DeprecatedColorTokens.blue40,
  '--color-blue-50': DeprecatedColorTokens.blue50,
  '--color-blue-60': DeprecatedColorTokens.blue60,
  '--color-blue-80': DeprecatedColorTokens.blue80,
  '--color-red-95': DeprecatedColorTokens.red95,
  '--color-red-80': DeprecatedColorTokens.red80,
  '--color-red-60': DeprecatedColorTokens.red60,
  '--color-red-45': DeprecatedColorTokens.red45,
  '--color-red-40': DeprecatedColorTokens.red40,
  '--color-green-90': DeprecatedColorTokens.green90,
  '--color-green-40': DeprecatedColorTokens.green40,
};

export enum DeprecatedColors {
  darkerBlue = 'var(--color-darker-blue)',
  darkBlue = 'var(--color-dark-blue)',
  blue = 'var(--color-blue)',
  darkGreen = 'var(--color-dark-green)',
  green = 'var(--color-green)',
  red = 'var(--color-red)',
  darkYellow = 'var(--color-dark-yellow)',
  yellow = 'var(--color-yellow)',
  black = 'var(--color-black)',
  white = 'var(--color-white)',
  white90 = 'var(--color-white-90)',
  white80 = 'var(--color-white-80)',
  white60 = 'var(--color-white-60)',
  white50 = 'var(--color-white-50)',
  white40 = 'var(--color-white-40)',
  white20 = 'var(--color-white-20)',
  white10 = 'var(--color-white-10)',
  blue10 = 'var(--color-blue-10)',
  blue20 = 'var(--color-blue-20)',
  blue40 = 'var(--color-blue-40)',
  blue50 = 'var(--color-blue-50)',
  blue60 = 'var(--color-blue-60)',
  blue80 = 'var(--color-blue-80)',
  red95 = 'var(--color-red-95)',
  red80 = 'var(--color-red-80)',
  red60 = 'var(--color-red-60)',
  red45 = 'var(--color-red-45)',
  red40 = 'var(--color-red-40)',
  green90 = 'var(--color-green-90)',
  green40 = 'var(--color-green-40)',
}
