import { ColorTokens } from '../tokens';

export const colors = {
  '--color-darker-blue': ColorTokens.darkBlue,
  '--color-dark-blue': ColorTokens.darkBlue,
  '--color-blue': ColorTokens.blue,
  '--color-dark-green': ColorTokens.darkGreen,
  '--color-green': ColorTokens.green,
  '--color-red': ColorTokens.red,
  '--color-darkYellow': ColorTokens.darkYellow,
  '--color-yellow': ColorTokens.yellow,
  '--color-black': ColorTokens.black,
  '--color-white': ColorTokens.white,
  '--color-white-90': ColorTokens.white90,
  '--color-white-80': ColorTokens.white80,
  '--color-white-60': ColorTokens.white60,
  '--color-white-50': ColorTokens.white50,
  '--color-white-40': ColorTokens.white40,
  '--color-white-20': ColorTokens.white20,
  '--color-white-10': ColorTokens.white10,
  '--color-blue10': ColorTokens.blue10,
  '--color-blue-20': ColorTokens.blue20,
  '--color-blue-40': ColorTokens.blue40,
  '--color-blue-50': ColorTokens.blue50,
  '--color-blue-60': ColorTokens.blue60,
  '--color-blue-80': ColorTokens.blue80,
  '--color-red-95': ColorTokens.red95,
  '--color-red-80': ColorTokens.red80,
  '--color-red-60': ColorTokens.red60,
  '--color-red-45': ColorTokens.red45,
  '--color-red-40': ColorTokens.red40,
  '--color-green-90': ColorTokens.green90,
  '--color-green-40': ColorTokens.green40,
};

export enum Colors {
  darkerBlue = 'var(--color-darker-blue)',
  darkBlue = 'var(--color-dark-blue)',
  blue = 'var(--color-blue)',
  darkGreen = 'var(--color-dark-green)',
  green = 'var(--color-green)',
  red = 'var(--color-red)',
  darkYellow = 'var(--color-dark-yellow)',
  yellow = 'var(--color-yellow)',
  black = 'var(--color-black)',
  white = 'var(--color-white)',
  white90 = 'var(--color-white-90)',
  white80 = 'var(--color-white-80)',
  white60 = 'var(--color-white-60)',
  white50 = 'var(--color-white-50)',
  white40 = 'var(--color-white-40)',
  white20 = 'var(--color-white-20)',
  white10 = 'var(--color-white-10)',
  blue10 = 'var(--color-blue-10)',
  blue20 = 'var(--color-blue-20)',
  blue40 = 'var(--color-blue-40)',
  blue50 = 'var(--color-blue-50)',
  blue60 = 'var(--color-blue-60)',
  blue80 = 'var(--color-blue-80)',
  red95 = 'var(--color-red-95)',
  red80 = 'var(--color-red-80)',
  red60 = 'var(--color-red-60)',
  red45 = 'var(--color-red-45)',
  red40 = 'var(--color-red-40)',
  green90 = 'var(--color-green-90)',
  green40 = 'var(--color-green-40)',
}
