import { colorTokens, DeprecatedColorTokens } from '../tokens';

export const deprecatedColors = {
  '--color-darker-blue': DeprecatedColorTokens.darkerBlue,
  '--color-dark-blue': DeprecatedColorTokens.darkBlue,
  '--color-blue': DeprecatedColorTokens.blue,
  '--color-dark-green': DeprecatedColorTokens.darkGreen,
  '--color-green': DeprecatedColorTokens.green,
  '--color-red': DeprecatedColorTokens.red,
  '--color-darkYellow': DeprecatedColorTokens.darkYellow,
  '--color-yellow': DeprecatedColorTokens.yellow,
  '--color-black': DeprecatedColorTokens.black,
  '--color-white': DeprecatedColorTokens.white,
  '--color-white-90': DeprecatedColorTokens.white90,
  '--color-white-80': DeprecatedColorTokens.white80,
  '--color-white-60': DeprecatedColorTokens.white60,
  '--color-white-50': DeprecatedColorTokens.white50,
  '--color-white-40': DeprecatedColorTokens.white40,
  '--color-white-20': DeprecatedColorTokens.white20,
  '--color-white-10': DeprecatedColorTokens.white10,
  '--color-blue10': DeprecatedColorTokens.blue10,
  '--color-blue-20': DeprecatedColorTokens.blue20,
  '--color-blue-40': DeprecatedColorTokens.blue40,
  '--color-blue-50': DeprecatedColorTokens.blue50,
  '--color-blue-60': DeprecatedColorTokens.blue60,
  '--color-blue-80': DeprecatedColorTokens.blue80,
  '--color-red-95': DeprecatedColorTokens.red95,
  '--color-red-80': DeprecatedColorTokens.red80,
  '--color-red-60': DeprecatedColorTokens.red60,
  '--color-red-45': DeprecatedColorTokens.red45,
  '--color-red-40': DeprecatedColorTokens.red40,
  '--color-green-90': DeprecatedColorTokens.green90,
  '--color-green-40': DeprecatedColorTokens.green40,
};

export enum DeprecatedColors {
  darkerBlue = 'var(--color-darker-blue)',
  darkBlue = 'var(--color-dark-blue)',
  blue = 'var(--color-blue)',
  darkGreen = 'var(--color-dark-green)',
  green = 'var(--color-green)',
  red = 'var(--color-red)',
  darkYellow = 'var(--color-dark-yellow)',
  yellow = 'var(--color-yellow)',
  black = 'var(--color-black)',
  white = 'var(--color-white)',
  white90 = 'var(--color-white-90)',
  white80 = 'var(--color-white-80)',
  white60 = 'var(--color-white-60)',
  white50 = 'var(--color-white-50)',
  white40 = 'var(--color-white-40)',
  white20 = 'var(--color-white-20)',
  white10 = 'var(--color-white-10)',
  blue10 = 'var(--color-blue-10)',
  blue20 = 'var(--color-blue-20)',
  blue40 = 'var(--color-blue-40)',
  blue50 = 'var(--color-blue-50)',
  blue60 = 'var(--color-blue-60)',
  blue80 = 'var(--color-blue-80)',
  red95 = 'var(--color-red-95)',
  red80 = 'var(--color-red-80)',
  red60 = 'var(--color-red-60)',
  red45 = 'var(--color-red-45)',
  red40 = 'var(--color-red-40)',
  green90 = 'var(--color-green-90)',
  green40 = 'var(--color-green-40)',
}

export const colorPrimitives = {
  '--color-white100': colorTokens.white100,
  '--color-white80': colorTokens.white80,
  '--color-white60': colorTokens.white60,
  '--color-white40': colorTokens.white40,
  '--color-white20': colorTokens.white20,

  '--color-black': colorTokens.black,
  '--color-black50': colorTokens.black50,

  '--color-brand-red': colorTokens.brandRed,
  '--color-brand-green': colorTokens.brandGreen,
  '--color-brand-yellow': colorTokens.brandYellow,
  '--color-brand-fur': colorTokens.brandFur,
  '--color-brand-nose': colorTokens.brandNose,
  '--color-brand-blue': colorTokens.brandBlue,
  '--color-brand-dark-blue': colorTokens.brandDarkBlue,

  '--color-green-alpha': colorTokens.greenAlpha,
  '--color-green80': colorTokens.green80,
  '--color-green40': colorTokens.green40,

  '--color-red': colorTokens.red,
  '--color-red-alpha': colorTokens.redAlpha,
  '--color-red80': colorTokens.red80,
  '--color-red40': colorTokens.red40,

  '--color-dark': colorTokens.dark,
  '--color-darker-blue50': colorTokens.darkerBlue50,
  '--color-darker-blue10': colorTokens.darkerBlue10,
  '--color-darker-blue10-alpha80': colorTokens.darkerBlue10Alpha80,
  '--color-darker-blue10-alpha40': colorTokens.darkerBlue10Alpha40,
  '--color-darker-blue50-alpha80': colorTokens.darkerBlue50Alpha80,

  '--color-blue10': colorTokens.blue10,
  '--color-blue20': colorTokens.blue20,
  '--color-blue40': colorTokens.blue40,
  '--color-blue50': colorTokens.blue50,
  '--color-blue60': colorTokens.blue60,
  '--color-blue80': colorTokens.blue80,

  '--color-white-on-dark-blue5': colorTokens.whiteOnDarkBlue5,
  '--color-white-on-dark-blue10': colorTokens.whiteOnDarkBlue10,
  '--color-white-on-dark-blue20': colorTokens.whiteOnDarkBlue20,
  '--color-white-on-dark-blue40': colorTokens.whiteOnDarkBlue40,
  '--color-white-on-dark-blue50': colorTokens.whiteOnDarkBlue50,
  '--color-white-on-dark-blue60': colorTokens.whiteOnDarkBlue60,
  '--color-white-on-dark-blue80': colorTokens.whiteOnDarkBlue80,

  '--color-white-on-blue5': colorTokens.whiteOnBlue5,
  '--color-white-on-blue10': colorTokens.whiteOnBlue10,
  '--color-white-on-blue20': colorTokens.whiteOnBlue20,
  '--color-white-on-blue40': colorTokens.whiteOnBlue40,
  '--color-white-on-blue50': colorTokens.whiteOnBlue50,
  '--color-white-on-blue60': colorTokens.whiteOnBlue60,
  '--color-white-on-blue80': colorTokens.whiteOnBlue80,

  '--color-chalk100': colorTokens.chalk100,
  '--color-chalk80': colorTokens.chalk80,
  '--color-chalk80Alpha': colorTokens.chalk80Alpha,
  '--color-chalk40Alpha': colorTokens.chalk40Alpha,
} as const;

export const colors = {
  white100: 'var(--color-white100)',
  white80: 'var(--color-white80)',
  white60: 'var(--color-white60)',
  white40: 'var(--color-white40)',
  white20: 'var(--color-white20)',

  black: 'var(--color-black)',
  black50: 'var(--color-black50)',

  brandRed: 'var(--color-brand-red)',
  brandGreen: 'var(--color-brand-green)',
  brandYellow: 'var(--color-brand-yellow)',
  brandFur: 'var(--color-brand-fur)',
  brandNose: 'var(--color-brand-nose)',
  brandBlue: 'var(--color-brand-blue)',
  brandDarkBlue: 'var(--color-brand-dark-blue)',

  greenAlpha: 'var(--color-green-alpha)',
  green80: 'var(--color-green80)',
  green40: 'var(--color-green40)',

  redAlpha: 'var(--color-red-alpha)',
  red: 'var(--color-red)',
  red80: 'var(--color-red80)',
  red40: 'var(--color-red40)',

  dark: 'var(--color-dark)',
  darkerBlue50: 'var(--color-darker-blue50)',
  darkerBlue10: 'var(--color-darker-blue10)',
  darkerBlue10Alpha80: 'var(--color-darker-blue10-alpha80)',
  darkerBlue10Alpha40: 'var(--color-darker-blue10-alpha40)',
  darkerBlue50Alpha80: 'var(--color-darker-blue50-alpha80)',

  blue10: 'var(--color-blue10)',
  blue20: 'var(--color-blue20)',
  blue40: 'var(--color-blue40)',
  blue50: 'var(--color-blue50)',
  blue60: 'var(--color-blue60)',
  blue80: 'var(--color-blue80)',

  whiteOnDarkBlue5: 'var(--color-white-on-dark-blue5)',
  whiteOnDarkBlue10: 'var(--color-white-on-dark-blue10)',
  whiteOnDarkBlue20: 'var(--color-white-on-dark-blue20)',
  whiteOnDarkBlue40: 'var(--color-white-on-dark-blue40)',
  whiteOnDarkBlue50: 'var(--color-white-on-dark-blue50)',
  whiteOnDarkBlue60: 'var(--color-white-on-dark-blue60)',
  whiteOnDarkBlue80: 'var(--color-white-on-dark-blue80)',

  whiteOnBlue5: 'var(--color-white-on-blue5)',
  whiteOnBlue10: 'var(--color-white-on-blue10)',
  whiteOnBlue20: 'var(--color-white-on-blue20)',
  whiteOnBlue40: 'var(--color-white-on-blue40)',
  whiteOnBlue50: 'var(--color-white-on-blue50)',
  whiteOnBlue60: 'var(--color-white-on-blue60)',
  whiteOnBlue80: 'var(--color-white-on-blue80)',

  chalk100: 'var(--color-chalk100)',
  chalk80: 'var(--color-chalk80)',
  chalk80Alpha: 'var(--color-chalk80Alpha)',
  chalk40Alpha: 'var(--color-chalk40Alpha)',
} as const;

export type Colors = keyof typeof colors;

export type ColorVariables = (typeof colors)[keyof typeof colors];
