// flow-typed signature: 34e9261773aa45e43be1b9185b282863
// flow-typed version: <<STUB>>/babel-plugin-inline-react-svg_v^0.4.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-inline-react-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-inline-react-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-inline-react-svg/lib/camelize' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-react-svg/lib/cssToObj' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-react-svg/lib/escapeBraces' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-react-svg/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-react-svg/lib/optimize' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-react-svg/lib/transformSvg' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-react-svg/test/fixtures/test' {
  declare module.exports: any;
}

declare module 'babel-plugin-inline-react-svg/test/sanity' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-inline-react-svg/lib/camelize.js' {
  declare module.exports: $Exports<'babel-plugin-inline-react-svg/lib/camelize'>;
}
declare module 'babel-plugin-inline-react-svg/lib/cssToObj.js' {
  declare module.exports: $Exports<'babel-plugin-inline-react-svg/lib/cssToObj'>;
}
declare module 'babel-plugin-inline-react-svg/lib/escapeBraces.js' {
  declare module.exports: $Exports<'babel-plugin-inline-react-svg/lib/escapeBraces'>;
}
declare module 'babel-plugin-inline-react-svg/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-inline-react-svg/lib/index'>;
}
declare module 'babel-plugin-inline-react-svg/lib/optimize.js' {
  declare module.exports: $Exports<'babel-plugin-inline-react-svg/lib/optimize'>;
}
declare module 'babel-plugin-inline-react-svg/lib/transformSvg.js' {
  declare module.exports: $Exports<'babel-plugin-inline-react-svg/lib/transformSvg'>;
}
declare module 'babel-plugin-inline-react-svg/test/fixtures/test.jsx' {
  declare module.exports: $Exports<'babel-plugin-inline-react-svg/test/fixtures/test'>;
}
declare module 'babel-plugin-inline-react-svg/test/sanity.js' {
  declare module.exports: $Exports<'babel-plugin-inline-react-svg/test/sanity'>;
}
