// flow-typed signature: 6b3e784f484f5c77b8b3397eafa767f0
// flow-typed version: <<STUB>>/d3-geo-projection_v^2.3.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-geo-projection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-geo-projection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-geo-projection/bin/read' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/bin/write' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/build/d3-geo-projection' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/build/d3-geo-projection.min' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/airy' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/aitoff' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/armadillo' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/august' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/baker' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/berghaus' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/bertin' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/boggs' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/bonne' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/bottomley' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/bromley' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/chamberlin' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/collignon' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/craig' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/craster' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/cylindricalEqualArea' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/cylindricalStereographic' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/eckert1' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/eckert2' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/eckert3' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/eckert4' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/eckert5' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/eckert6' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/eisenlohr' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/elliptic' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/fahey' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/foucaut' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/gilbert' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/gingery' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/ginzburg4' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/ginzburg5' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/ginzburg6' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/ginzburg8' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/ginzburg9' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/ginzburgPolyconic' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/gringorten' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/guyou' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/hammer' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/hammerRetroazimuthal' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/healpix' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/hill' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/homolosine' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/interrupted/boggs' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/interrupted/homolosine' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/interrupted/index' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/interrupted/mollweide' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/interrupted/mollweideHemispheres' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/interrupted/sinuMollweide' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/interrupted/sinusoidal' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/kavrayskiy7' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/lagrange' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/larrivee' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/laskowski' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/littrow' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/loximuthal' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/math' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/miller' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/modifiedStereographic' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/mollweide' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/mtFlatPolarParabolic' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/mtFlatPolarQuartic' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/mtFlatPolarSinusoidal' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/naturalEarth2' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/nellHammer' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/noop' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/parallel1' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/patterson' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/polyconic' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/polyhedral/butterfly' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/polyhedral/collignon' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/polyhedral/cube' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/polyhedral/index' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/polyhedral/matrix' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/polyhedral/octahedron' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/polyhedral/waterman' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/project/clockwise' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/project/contains' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/project/index' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/quantize' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/quincuncial/gringorten' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/quincuncial/index' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/quincuncial/peirce' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/rectangularPolyconic' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/robinson' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/satellite' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/sinuMollweide' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/sinusoidal' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/square' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/stitch' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/times' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/twoPoint' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/twoPointAzimuthal' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/twoPointEquidistant' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/vanDerGrinten' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/vanDerGrinten2' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/vanDerGrinten3' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/vanDerGrinten4' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/wagner4' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/wagner6' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/wagner7' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/wiechel' {
  declare module.exports: any;
}

declare module 'd3-geo-projection/src/winkel3' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-geo-projection/bin/read.js' {
  declare module.exports: $Exports<'d3-geo-projection/bin/read'>;
}
declare module 'd3-geo-projection/bin/write.js' {
  declare module.exports: $Exports<'d3-geo-projection/bin/write'>;
}
declare module 'd3-geo-projection/build/d3-geo-projection.js' {
  declare module.exports: $Exports<'d3-geo-projection/build/d3-geo-projection'>;
}
declare module 'd3-geo-projection/build/d3-geo-projection.min.js' {
  declare module.exports: $Exports<'d3-geo-projection/build/d3-geo-projection.min'>;
}
declare module 'd3-geo-projection/index' {
  declare module.exports: $Exports<'d3-geo-projection'>;
}
declare module 'd3-geo-projection/index.js' {
  declare module.exports: $Exports<'d3-geo-projection'>;
}
declare module 'd3-geo-projection/rollup.config.js' {
  declare module.exports: $Exports<'d3-geo-projection/rollup.config'>;
}
declare module 'd3-geo-projection/src/airy.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/airy'>;
}
declare module 'd3-geo-projection/src/aitoff.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/aitoff'>;
}
declare module 'd3-geo-projection/src/armadillo.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/armadillo'>;
}
declare module 'd3-geo-projection/src/august.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/august'>;
}
declare module 'd3-geo-projection/src/baker.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/baker'>;
}
declare module 'd3-geo-projection/src/berghaus.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/berghaus'>;
}
declare module 'd3-geo-projection/src/bertin.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/bertin'>;
}
declare module 'd3-geo-projection/src/boggs.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/boggs'>;
}
declare module 'd3-geo-projection/src/bonne.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/bonne'>;
}
declare module 'd3-geo-projection/src/bottomley.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/bottomley'>;
}
declare module 'd3-geo-projection/src/bromley.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/bromley'>;
}
declare module 'd3-geo-projection/src/chamberlin.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/chamberlin'>;
}
declare module 'd3-geo-projection/src/collignon.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/collignon'>;
}
declare module 'd3-geo-projection/src/craig.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/craig'>;
}
declare module 'd3-geo-projection/src/craster.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/craster'>;
}
declare module 'd3-geo-projection/src/cylindricalEqualArea.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/cylindricalEqualArea'>;
}
declare module 'd3-geo-projection/src/cylindricalStereographic.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/cylindricalStereographic'>;
}
declare module 'd3-geo-projection/src/eckert1.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/eckert1'>;
}
declare module 'd3-geo-projection/src/eckert2.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/eckert2'>;
}
declare module 'd3-geo-projection/src/eckert3.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/eckert3'>;
}
declare module 'd3-geo-projection/src/eckert4.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/eckert4'>;
}
declare module 'd3-geo-projection/src/eckert5.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/eckert5'>;
}
declare module 'd3-geo-projection/src/eckert6.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/eckert6'>;
}
declare module 'd3-geo-projection/src/eisenlohr.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/eisenlohr'>;
}
declare module 'd3-geo-projection/src/elliptic.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/elliptic'>;
}
declare module 'd3-geo-projection/src/fahey.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/fahey'>;
}
declare module 'd3-geo-projection/src/foucaut.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/foucaut'>;
}
declare module 'd3-geo-projection/src/gilbert.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/gilbert'>;
}
declare module 'd3-geo-projection/src/gingery.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/gingery'>;
}
declare module 'd3-geo-projection/src/ginzburg4.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/ginzburg4'>;
}
declare module 'd3-geo-projection/src/ginzburg5.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/ginzburg5'>;
}
declare module 'd3-geo-projection/src/ginzburg6.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/ginzburg6'>;
}
declare module 'd3-geo-projection/src/ginzburg8.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/ginzburg8'>;
}
declare module 'd3-geo-projection/src/ginzburg9.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/ginzburg9'>;
}
declare module 'd3-geo-projection/src/ginzburgPolyconic.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/ginzburgPolyconic'>;
}
declare module 'd3-geo-projection/src/gringorten.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/gringorten'>;
}
declare module 'd3-geo-projection/src/guyou.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/guyou'>;
}
declare module 'd3-geo-projection/src/hammer.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/hammer'>;
}
declare module 'd3-geo-projection/src/hammerRetroazimuthal.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/hammerRetroazimuthal'>;
}
declare module 'd3-geo-projection/src/healpix.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/healpix'>;
}
declare module 'd3-geo-projection/src/hill.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/hill'>;
}
declare module 'd3-geo-projection/src/homolosine.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/homolosine'>;
}
declare module 'd3-geo-projection/src/interrupted/boggs.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/interrupted/boggs'>;
}
declare module 'd3-geo-projection/src/interrupted/homolosine.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/interrupted/homolosine'>;
}
declare module 'd3-geo-projection/src/interrupted/index.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/interrupted/index'>;
}
declare module 'd3-geo-projection/src/interrupted/mollweide.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/interrupted/mollweide'>;
}
declare module 'd3-geo-projection/src/interrupted/mollweideHemispheres.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/interrupted/mollweideHemispheres'>;
}
declare module 'd3-geo-projection/src/interrupted/sinuMollweide.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/interrupted/sinuMollweide'>;
}
declare module 'd3-geo-projection/src/interrupted/sinusoidal.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/interrupted/sinusoidal'>;
}
declare module 'd3-geo-projection/src/kavrayskiy7.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/kavrayskiy7'>;
}
declare module 'd3-geo-projection/src/lagrange.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/lagrange'>;
}
declare module 'd3-geo-projection/src/larrivee.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/larrivee'>;
}
declare module 'd3-geo-projection/src/laskowski.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/laskowski'>;
}
declare module 'd3-geo-projection/src/littrow.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/littrow'>;
}
declare module 'd3-geo-projection/src/loximuthal.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/loximuthal'>;
}
declare module 'd3-geo-projection/src/math.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/math'>;
}
declare module 'd3-geo-projection/src/miller.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/miller'>;
}
declare module 'd3-geo-projection/src/modifiedStereographic.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/modifiedStereographic'>;
}
declare module 'd3-geo-projection/src/mollweide.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/mollweide'>;
}
declare module 'd3-geo-projection/src/mtFlatPolarParabolic.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/mtFlatPolarParabolic'>;
}
declare module 'd3-geo-projection/src/mtFlatPolarQuartic.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/mtFlatPolarQuartic'>;
}
declare module 'd3-geo-projection/src/mtFlatPolarSinusoidal.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/mtFlatPolarSinusoidal'>;
}
declare module 'd3-geo-projection/src/naturalEarth2.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/naturalEarth2'>;
}
declare module 'd3-geo-projection/src/nellHammer.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/nellHammer'>;
}
declare module 'd3-geo-projection/src/noop.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/noop'>;
}
declare module 'd3-geo-projection/src/parallel1.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/parallel1'>;
}
declare module 'd3-geo-projection/src/patterson.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/patterson'>;
}
declare module 'd3-geo-projection/src/polyconic.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/polyconic'>;
}
declare module 'd3-geo-projection/src/polyhedral/butterfly.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/polyhedral/butterfly'>;
}
declare module 'd3-geo-projection/src/polyhedral/collignon.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/polyhedral/collignon'>;
}
declare module 'd3-geo-projection/src/polyhedral/cube.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/polyhedral/cube'>;
}
declare module 'd3-geo-projection/src/polyhedral/index.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/polyhedral/index'>;
}
declare module 'd3-geo-projection/src/polyhedral/matrix.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/polyhedral/matrix'>;
}
declare module 'd3-geo-projection/src/polyhedral/octahedron.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/polyhedral/octahedron'>;
}
declare module 'd3-geo-projection/src/polyhedral/waterman.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/polyhedral/waterman'>;
}
declare module 'd3-geo-projection/src/project/clockwise.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/project/clockwise'>;
}
declare module 'd3-geo-projection/src/project/contains.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/project/contains'>;
}
declare module 'd3-geo-projection/src/project/index.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/project/index'>;
}
declare module 'd3-geo-projection/src/quantize.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/quantize'>;
}
declare module 'd3-geo-projection/src/quincuncial/gringorten.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/quincuncial/gringorten'>;
}
declare module 'd3-geo-projection/src/quincuncial/index.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/quincuncial/index'>;
}
declare module 'd3-geo-projection/src/quincuncial/peirce.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/quincuncial/peirce'>;
}
declare module 'd3-geo-projection/src/rectangularPolyconic.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/rectangularPolyconic'>;
}
declare module 'd3-geo-projection/src/robinson.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/robinson'>;
}
declare module 'd3-geo-projection/src/satellite.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/satellite'>;
}
declare module 'd3-geo-projection/src/sinuMollweide.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/sinuMollweide'>;
}
declare module 'd3-geo-projection/src/sinusoidal.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/sinusoidal'>;
}
declare module 'd3-geo-projection/src/square.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/square'>;
}
declare module 'd3-geo-projection/src/stitch.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/stitch'>;
}
declare module 'd3-geo-projection/src/times.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/times'>;
}
declare module 'd3-geo-projection/src/twoPoint.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/twoPoint'>;
}
declare module 'd3-geo-projection/src/twoPointAzimuthal.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/twoPointAzimuthal'>;
}
declare module 'd3-geo-projection/src/twoPointEquidistant.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/twoPointEquidistant'>;
}
declare module 'd3-geo-projection/src/vanDerGrinten.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/vanDerGrinten'>;
}
declare module 'd3-geo-projection/src/vanDerGrinten2.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/vanDerGrinten2'>;
}
declare module 'd3-geo-projection/src/vanDerGrinten3.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/vanDerGrinten3'>;
}
declare module 'd3-geo-projection/src/vanDerGrinten4.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/vanDerGrinten4'>;
}
declare module 'd3-geo-projection/src/wagner4.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/wagner4'>;
}
declare module 'd3-geo-projection/src/wagner6.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/wagner6'>;
}
declare module 'd3-geo-projection/src/wagner7.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/wagner7'>;
}
declare module 'd3-geo-projection/src/wiechel.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/wiechel'>;
}
declare module 'd3-geo-projection/src/winkel3.js' {
  declare module.exports: $Exports<'d3-geo-projection/src/winkel3'>;
}
