// flow-typed signature: b92711eaa00b7c030c9547ddda0f2509
// flow-typed version: <<STUB>>/electron-sudo_vhttps://github.com/eriklarko/electron-sudo.git/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-sudo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-sudo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-sudo/dist/index' {
  declare module.exports: any;
}

declare module 'electron-sudo/src/index' {
  declare module.exports: any;
}

declare module 'electron-sudo/src/lib/sudoer' {
  declare module.exports: any;
}

declare module 'electron-sudo/src/lib/utils' {
  declare module.exports: any;
}

declare module 'electron-sudo/tests/index' {
  declare module.exports: any;
}

declare module 'electron-sudo/webpack/chmod' {
  declare module.exports: any;
}

declare module 'electron-sudo/webpack/config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-sudo/dist/index.js' {
  declare module.exports: $Exports<'electron-sudo/dist/index'>;
}
declare module 'electron-sudo/src/index.js' {
  declare module.exports: $Exports<'electron-sudo/src/index'>;
}
declare module 'electron-sudo/src/lib/sudoer.js' {
  declare module.exports: $Exports<'electron-sudo/src/lib/sudoer'>;
}
declare module 'electron-sudo/src/lib/utils.js' {
  declare module.exports: $Exports<'electron-sudo/src/lib/utils'>;
}
declare module 'electron-sudo/tests/index.js' {
  declare module.exports: $Exports<'electron-sudo/tests/index'>;
}
declare module 'electron-sudo/webpack/chmod.js' {
  declare module.exports: $Exports<'electron-sudo/webpack/chmod'>;
}
declare module 'electron-sudo/webpack/config.babel.js' {
  declare module.exports: $Exports<'electron-sudo/webpack/config.babel'>;
}
