// flow-typed signature: a2b1f23f2fe8286d15c43e28d1f28578
// flow-typed version: <<STUB>>/electron-log_v2.2.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-log/lib/format' {
  declare module.exports: any;
}

declare module 'electron-log/lib/log' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/console' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/file/find-log-path' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/file/get-app-name' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/file/index' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/log-s' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/renderer-console' {
  declare module.exports: any;
}

declare module 'electron-log/main' {
  declare module.exports: any;
}

declare module 'electron-log/renderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-log/index' {
  declare module.exports: $Exports<'electron-log'>;
}
declare module 'electron-log/index.js' {
  declare module.exports: $Exports<'electron-log'>;
}
declare module 'electron-log/lib/format.js' {
  declare module.exports: $Exports<'electron-log/lib/format'>;
}
declare module 'electron-log/lib/log.js' {
  declare module.exports: $Exports<'electron-log/lib/log'>;
}
declare module 'electron-log/lib/transports/console.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/console'>;
}
declare module 'electron-log/lib/transports/file/find-log-path.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/file/find-log-path'>;
}
declare module 'electron-log/lib/transports/file/get-app-name.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/file/get-app-name'>;
}
declare module 'electron-log/lib/transports/file/index.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/file/index'>;
}
declare module 'electron-log/lib/transports/log-s.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/log-s'>;
}
declare module 'electron-log/lib/transports/renderer-console.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/renderer-console'>;
}
declare module 'electron-log/main.js' {
  declare module.exports: $Exports<'electron-log/main'>;
}
declare module 'electron-log/renderer.js' {
  declare module.exports: $Exports<'electron-log/renderer'>;
}
