// flow-typed signature: b8f0a996b5556af2e69d8a12dc223841
// flow-typed version: <<STUB>>/esdoc_v^0.5.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc/out/src/BuiltinExternal/ECMAScriptExternal' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/BuiltinExternal/WebAPIExternal' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/AbstractDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/AssignmentDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/ClassDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/ClassPropertyDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/ExternalDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/FileDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/FunctionDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/MemberDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/MethodDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/TestDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/TestFileDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/TypedefDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Doc/VariableDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/ESDoc' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/ESDocCLI' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Factory/DocFactory' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Factory/TestDocFactory' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Parser/CommentParser' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Parser/ESParser' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Parser/ParamParser' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Plugin/Plugin' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/ASTDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/ClassDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/CoverageBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/DocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/DocResolver' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/FileDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/IdentifiersDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/IndexDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/LintDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/ManualDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/SearchIndexBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/SingleDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/SourceDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/StaticFileBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/template/script/inherited-summary' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/template/script/inner-link' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/template/script/manual' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/template/script/patch-for-local' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/template/script/prettify/prettify' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/template/script/pretty-print' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/template/script/search' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/template/script/test-summary' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/TestDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/TestFileDocBuilder' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/Builder/util' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Publisher/publish' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Typedef/typedef' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/ASTNodeContainer' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/ASTUtil' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/InvalidCodeLogger' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/NamingUtil' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/NPMUtil' {
  declare module.exports: any;
}

declare module 'esdoc/out/src/Util/PathResolver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc/out/src/BuiltinExternal/ECMAScriptExternal.js' {
  declare module.exports: $Exports<'esdoc/out/src/BuiltinExternal/ECMAScriptExternal'>;
}
declare module 'esdoc/out/src/BuiltinExternal/WebAPIExternal.js' {
  declare module.exports: $Exports<'esdoc/out/src/BuiltinExternal/WebAPIExternal'>;
}
declare module 'esdoc/out/src/Doc/AbstractDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/AbstractDoc'>;
}
declare module 'esdoc/out/src/Doc/AssignmentDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/AssignmentDoc'>;
}
declare module 'esdoc/out/src/Doc/ClassDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/ClassDoc'>;
}
declare module 'esdoc/out/src/Doc/ClassPropertyDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/ClassPropertyDoc'>;
}
declare module 'esdoc/out/src/Doc/ExternalDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/ExternalDoc'>;
}
declare module 'esdoc/out/src/Doc/FileDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/FileDoc'>;
}
declare module 'esdoc/out/src/Doc/FunctionDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/FunctionDoc'>;
}
declare module 'esdoc/out/src/Doc/MemberDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/MemberDoc'>;
}
declare module 'esdoc/out/src/Doc/MethodDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/MethodDoc'>;
}
declare module 'esdoc/out/src/Doc/TestDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/TestDoc'>;
}
declare module 'esdoc/out/src/Doc/TestFileDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/TestFileDoc'>;
}
declare module 'esdoc/out/src/Doc/TypedefDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/TypedefDoc'>;
}
declare module 'esdoc/out/src/Doc/VariableDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/Doc/VariableDoc'>;
}
declare module 'esdoc/out/src/ESDoc.js' {
  declare module.exports: $Exports<'esdoc/out/src/ESDoc'>;
}
declare module 'esdoc/out/src/ESDocCLI.js' {
  declare module.exports: $Exports<'esdoc/out/src/ESDocCLI'>;
}
declare module 'esdoc/out/src/Factory/DocFactory.js' {
  declare module.exports: $Exports<'esdoc/out/src/Factory/DocFactory'>;
}
declare module 'esdoc/out/src/Factory/TestDocFactory.js' {
  declare module.exports: $Exports<'esdoc/out/src/Factory/TestDocFactory'>;
}
declare module 'esdoc/out/src/Parser/CommentParser.js' {
  declare module.exports: $Exports<'esdoc/out/src/Parser/CommentParser'>;
}
declare module 'esdoc/out/src/Parser/ESParser.js' {
  declare module.exports: $Exports<'esdoc/out/src/Parser/ESParser'>;
}
declare module 'esdoc/out/src/Parser/ParamParser.js' {
  declare module.exports: $Exports<'esdoc/out/src/Parser/ParamParser'>;
}
declare module 'esdoc/out/src/Plugin/Plugin.js' {
  declare module.exports: $Exports<'esdoc/out/src/Plugin/Plugin'>;
}
declare module 'esdoc/out/src/Publisher/Builder/ASTDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/ASTDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/ClassDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/ClassDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/CoverageBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/CoverageBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/DocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/DocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/DocResolver.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/DocResolver'>;
}
declare module 'esdoc/out/src/Publisher/Builder/FileDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/FileDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/IdentifiersDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/IdentifiersDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/IndexDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/IndexDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/LintDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/LintDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/ManualDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/ManualDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/SearchIndexBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/SearchIndexBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/SingleDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/SingleDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/SourceDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/SourceDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/StaticFileBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/StaticFileBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/template/script/inherited-summary.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/template/script/inherited-summary'>;
}
declare module 'esdoc/out/src/Publisher/Builder/template/script/inner-link.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/template/script/inner-link'>;
}
declare module 'esdoc/out/src/Publisher/Builder/template/script/manual.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/template/script/manual'>;
}
declare module 'esdoc/out/src/Publisher/Builder/template/script/patch-for-local.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/template/script/patch-for-local'>;
}
declare module 'esdoc/out/src/Publisher/Builder/template/script/prettify/prettify.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/template/script/prettify/prettify'>;
}
declare module 'esdoc/out/src/Publisher/Builder/template/script/pretty-print.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/template/script/pretty-print'>;
}
declare module 'esdoc/out/src/Publisher/Builder/template/script/search.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/template/script/search'>;
}
declare module 'esdoc/out/src/Publisher/Builder/template/script/test-summary.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/template/script/test-summary'>;
}
declare module 'esdoc/out/src/Publisher/Builder/TestDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/TestDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/TestFileDocBuilder.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/TestFileDocBuilder'>;
}
declare module 'esdoc/out/src/Publisher/Builder/util.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/Builder/util'>;
}
declare module 'esdoc/out/src/Publisher/publish.js' {
  declare module.exports: $Exports<'esdoc/out/src/Publisher/publish'>;
}
declare module 'esdoc/out/src/Typedef/typedef.js' {
  declare module.exports: $Exports<'esdoc/out/src/Typedef/typedef'>;
}
declare module 'esdoc/out/src/Util/ASTNodeContainer.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/ASTNodeContainer'>;
}
declare module 'esdoc/out/src/Util/ASTUtil.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/ASTUtil'>;
}
declare module 'esdoc/out/src/Util/InvalidCodeLogger.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/InvalidCodeLogger'>;
}
declare module 'esdoc/out/src/Util/NamingUtil.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/NamingUtil'>;
}
declare module 'esdoc/out/src/Util/NPMUtil.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/NPMUtil'>;
}
declare module 'esdoc/out/src/Util/PathResolver.js' {
  declare module.exports: $Exports<'esdoc/out/src/Util/PathResolver'>;
}
