// flow-typed signature: 84dfb2625a302eb80d469e7ded1bfbd2
// flow-typed version: <<STUB>>/jsonrpc-lite_v^1.2.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonrpc-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonrpc-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonrpc-lite/jsonrpc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonrpc-lite/jsonrpc.js' {
  declare module.exports: $Exports<'jsonrpc-lite/jsonrpc'>;
}
