// flow-typed signature: 6b45d9f4c04bf023928ad76a3623f414
// flow-typed version: <<STUB>>/mapbox-gl_v^0.37.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapbox-gl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapbox-gl/dist/mapbox-gl-dev' {
  declare module.exports: any;
}

declare module 'mapbox-gl/dist/mapbox-gl' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-interfaces/mapbox-gl-js-test' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-interfaces/mapbox-gl-supported' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-interfaces/mapbox-unitbezier' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-interfaces/point-geometry' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-interfaces/unitbezier' {
  declare module.exports: any;
}

declare module 'mapbox-gl/plugins/src/mapbox-gl-directions/v3.1.1/mapbox-gl-directions' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/array_group' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/circle_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/fill_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/fill_extrusion_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/line_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/symbol_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/buffer_group' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/buffer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/element_array_type' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/extent' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/feature_index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/load_geometry' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/pos_array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/program_configuration' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/raster_bounds_array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/vertex_array_type' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/coordinate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/lng_lat_bounds' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/lng_lat' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/transform' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_background' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_circle' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_collision_debug' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_debug' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_fill_extrusion' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_fill' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_line' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_raster' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_symbol' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/frame_history' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/line_atlas' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/painter' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/pattern' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/shaders' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/vertex_array_object' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/shaders/encode_attribute' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/canvas_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/geojson_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/geojson_worker_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/geojson_wrapper' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/image_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/load_tilejson' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/pixels_to_tile_units' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/query_features' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/raster_tile_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/rtl_text_plugin' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/source_cache' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/tile_bounds' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/tile_coord' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/tile' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/vector_tile_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/vector_tile_worker_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/video_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/worker_tile' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/worker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/composite' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/declass' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/deref' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/diff' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/error/parsing_error' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/error/validation_error' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/feature_filter/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/format' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/function/color_spaces' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/function/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/group_by_layout' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate/v7' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate/v8' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate/v9' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/minifyify_style_spec' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/reference/latest' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/extend' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/get_type' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/interpolate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/parse_color' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/ref_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/unbundle_jsonlint' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate_style' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate_style.min' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/latest' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_boolean' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_color' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_constants' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_enum' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_filter' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_function' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_glyphs_url' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_layout_property' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_light' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_number' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_object' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_paint_property' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_property' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_string' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/animation_loop' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/image_sprite' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/light' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_declaration' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer_index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/circle_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/fill_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/line_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/symbol_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_transition' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/validate_style' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/anchor' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/check_max_angle' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/clip_line' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/collision_box' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/collision_feature' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/collision_tile' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/get_anchors' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/glyph_atlas' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/glyph_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/mergelines' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/quads' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/shaping' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/sprite_atlas' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/transform_text' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/bind_handlers' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/camera' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/attribution_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/fullscreen_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/geolocate_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/logo_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/navigation_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/scale_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/box_zoom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/dblclick_zoom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/drag_pan' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/drag_rotate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/keyboard' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/scroll_zoom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/touch_zoom_rotate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/hash' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/map' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/marker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/popup' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/actor' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/ajax' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/browser' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/browser/web_worker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/browser/window' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/classify_rings' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/config' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/dictionary_coder' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/dispatcher' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/dom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/evented' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/find_pole_of_inaccessibility' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/global_worker_pool' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/glyphs' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/intersection_tests' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/is_char_in_unicode_block' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/lru_cache' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/mapbox' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/script_detection' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/smart_wrap' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/struct_array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/token' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/util' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/vectortile_to_geojson' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/verticalize_punctuation' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/web_worker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/window' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/worker_pool' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapbox-gl/dist/mapbox-gl-dev.js' {
  declare module.exports: $Exports<'mapbox-gl/dist/mapbox-gl-dev'>;
}
declare module 'mapbox-gl/dist/mapbox-gl.js' {
  declare module.exports: $Exports<'mapbox-gl/dist/mapbox-gl'>;
}
declare module 'mapbox-gl/flow-interfaces/mapbox-gl-js-test.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-interfaces/mapbox-gl-js-test'>;
}
declare module 'mapbox-gl/flow-interfaces/mapbox-gl-supported.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-interfaces/mapbox-gl-supported'>;
}
declare module 'mapbox-gl/flow-interfaces/mapbox-unitbezier.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-interfaces/mapbox-unitbezier'>;
}
declare module 'mapbox-gl/flow-interfaces/point-geometry.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-interfaces/point-geometry'>;
}
declare module 'mapbox-gl/flow-interfaces/unitbezier.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-interfaces/unitbezier'>;
}
declare module 'mapbox-gl/plugins/src/mapbox-gl-directions/v3.1.1/mapbox-gl-directions.js' {
  declare module.exports: $Exports<'mapbox-gl/plugins/src/mapbox-gl-directions/v3.1.1/mapbox-gl-directions'>;
}
declare module 'mapbox-gl/src/data/array_group.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/array_group'>;
}
declare module 'mapbox-gl/src/data/bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/circle_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/circle_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/fill_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/fill_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/fill_extrusion_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/fill_extrusion_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/line_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/line_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/symbol_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/symbol_bucket'>;
}
declare module 'mapbox-gl/src/data/buffer_group.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/buffer_group'>;
}
declare module 'mapbox-gl/src/data/buffer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/buffer'>;
}
declare module 'mapbox-gl/src/data/element_array_type.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/element_array_type'>;
}
declare module 'mapbox-gl/src/data/extent.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/extent'>;
}
declare module 'mapbox-gl/src/data/feature_index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/feature_index'>;
}
declare module 'mapbox-gl/src/data/load_geometry.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/load_geometry'>;
}
declare module 'mapbox-gl/src/data/pos_array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/pos_array'>;
}
declare module 'mapbox-gl/src/data/program_configuration.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/program_configuration'>;
}
declare module 'mapbox-gl/src/data/raster_bounds_array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/raster_bounds_array'>;
}
declare module 'mapbox-gl/src/data/vertex_array_type.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/vertex_array_type'>;
}
declare module 'mapbox-gl/src/geo/coordinate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/coordinate'>;
}
declare module 'mapbox-gl/src/geo/lng_lat_bounds.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/lng_lat_bounds'>;
}
declare module 'mapbox-gl/src/geo/lng_lat.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/lng_lat'>;
}
declare module 'mapbox-gl/src/geo/transform.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/transform'>;
}
declare module 'mapbox-gl/src/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/index'>;
}
declare module 'mapbox-gl/src/render/draw_background.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_background'>;
}
declare module 'mapbox-gl/src/render/draw_circle.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_circle'>;
}
declare module 'mapbox-gl/src/render/draw_collision_debug.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_collision_debug'>;
}
declare module 'mapbox-gl/src/render/draw_debug.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_debug'>;
}
declare module 'mapbox-gl/src/render/draw_fill_extrusion.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_fill_extrusion'>;
}
declare module 'mapbox-gl/src/render/draw_fill.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_fill'>;
}
declare module 'mapbox-gl/src/render/draw_line.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_line'>;
}
declare module 'mapbox-gl/src/render/draw_raster.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_raster'>;
}
declare module 'mapbox-gl/src/render/draw_symbol.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_symbol'>;
}
declare module 'mapbox-gl/src/render/frame_history.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/frame_history'>;
}
declare module 'mapbox-gl/src/render/line_atlas.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/line_atlas'>;
}
declare module 'mapbox-gl/src/render/painter.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/painter'>;
}
declare module 'mapbox-gl/src/render/pattern.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/pattern'>;
}
declare module 'mapbox-gl/src/render/shaders.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/shaders'>;
}
declare module 'mapbox-gl/src/render/vertex_array_object.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/vertex_array_object'>;
}
declare module 'mapbox-gl/src/shaders/encode_attribute.js' {
  declare module.exports: $Exports<'mapbox-gl/src/shaders/encode_attribute'>;
}
declare module 'mapbox-gl/src/source/canvas_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/canvas_source'>;
}
declare module 'mapbox-gl/src/source/geojson_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/geojson_source'>;
}
declare module 'mapbox-gl/src/source/geojson_worker_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/geojson_worker_source'>;
}
declare module 'mapbox-gl/src/source/geojson_wrapper.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/geojson_wrapper'>;
}
declare module 'mapbox-gl/src/source/image_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/image_source'>;
}
declare module 'mapbox-gl/src/source/load_tilejson.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/load_tilejson'>;
}
declare module 'mapbox-gl/src/source/pixels_to_tile_units.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/pixels_to_tile_units'>;
}
declare module 'mapbox-gl/src/source/query_features.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/query_features'>;
}
declare module 'mapbox-gl/src/source/raster_tile_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/raster_tile_source'>;
}
declare module 'mapbox-gl/src/source/rtl_text_plugin.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/rtl_text_plugin'>;
}
declare module 'mapbox-gl/src/source/source_cache.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/source_cache'>;
}
declare module 'mapbox-gl/src/source/source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/source'>;
}
declare module 'mapbox-gl/src/source/tile_bounds.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/tile_bounds'>;
}
declare module 'mapbox-gl/src/source/tile_coord.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/tile_coord'>;
}
declare module 'mapbox-gl/src/source/tile.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/tile'>;
}
declare module 'mapbox-gl/src/source/vector_tile_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/vector_tile_source'>;
}
declare module 'mapbox-gl/src/source/vector_tile_worker_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/vector_tile_worker_source'>;
}
declare module 'mapbox-gl/src/source/video_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/video_source'>;
}
declare module 'mapbox-gl/src/source/worker_tile.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/worker_tile'>;
}
declare module 'mapbox-gl/src/source/worker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/worker'>;
}
declare module 'mapbox-gl/src/style-spec/composite.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/composite'>;
}
declare module 'mapbox-gl/src/style-spec/declass.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/declass'>;
}
declare module 'mapbox-gl/src/style-spec/deref.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/deref'>;
}
declare module 'mapbox-gl/src/style-spec/diff.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/diff'>;
}
declare module 'mapbox-gl/src/style-spec/error/parsing_error.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/error/parsing_error'>;
}
declare module 'mapbox-gl/src/style-spec/error/validation_error.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/error/validation_error'>;
}
declare module 'mapbox-gl/src/style-spec/feature_filter/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/feature_filter/index'>;
}
declare module 'mapbox-gl/src/style-spec/format.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/format'>;
}
declare module 'mapbox-gl/src/style-spec/function/color_spaces.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/function/color_spaces'>;
}
declare module 'mapbox-gl/src/style-spec/function/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/function/index'>;
}
declare module 'mapbox-gl/src/style-spec/group_by_layout.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/group_by_layout'>;
}
declare module 'mapbox-gl/src/style-spec/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/index'>;
}
declare module 'mapbox-gl/src/style-spec/migrate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate'>;
}
declare module 'mapbox-gl/src/style-spec/migrate/v7.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate/v7'>;
}
declare module 'mapbox-gl/src/style-spec/migrate/v8.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate/v8'>;
}
declare module 'mapbox-gl/src/style-spec/migrate/v9.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate/v9'>;
}
declare module 'mapbox-gl/src/style-spec/minifyify_style_spec.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/minifyify_style_spec'>;
}
declare module 'mapbox-gl/src/style-spec/reference/latest.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/reference/latest'>;
}
declare module 'mapbox-gl/src/style-spec/util/extend.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/extend'>;
}
declare module 'mapbox-gl/src/style-spec/util/get_type.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/get_type'>;
}
declare module 'mapbox-gl/src/style-spec/util/interpolate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/interpolate'>;
}
declare module 'mapbox-gl/src/style-spec/util/parse_color.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/parse_color'>;
}
declare module 'mapbox-gl/src/style-spec/util/ref_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/ref_properties'>;
}
declare module 'mapbox-gl/src/style-spec/util/unbundle_jsonlint.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/unbundle_jsonlint'>;
}
declare module 'mapbox-gl/src/style-spec/validate_style.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate_style'>;
}
declare module 'mapbox-gl/src/style-spec/validate_style.min.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate_style.min'>;
}
declare module 'mapbox-gl/src/style-spec/validate/latest.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/latest'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_array'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_boolean.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_boolean'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_color.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_color'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_constants.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_constants'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_enum.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_enum'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_filter.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_filter'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_function.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_function'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_glyphs_url.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_glyphs_url'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_layer'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_layout_property.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_layout_property'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_light.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_light'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_number.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_number'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_object.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_object'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_paint_property.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_paint_property'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_property.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_property'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_source'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_string.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_string'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate'>;
}
declare module 'mapbox-gl/src/style/animation_loop.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/animation_loop'>;
}
declare module 'mapbox-gl/src/style/image_sprite.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/image_sprite'>;
}
declare module 'mapbox-gl/src/style/light.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/light'>;
}
declare module 'mapbox-gl/src/style/style_declaration.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_declaration'>;
}
declare module 'mapbox-gl/src/style/style_layer_index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer_index'>;
}
declare module 'mapbox-gl/src/style/style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/circle_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/circle_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/fill_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/fill_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/line_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/line_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/symbol_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/symbol_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_transition.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_transition'>;
}
declare module 'mapbox-gl/src/style/style.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style'>;
}
declare module 'mapbox-gl/src/style/validate_style.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/validate_style'>;
}
declare module 'mapbox-gl/src/symbol/anchor.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/anchor'>;
}
declare module 'mapbox-gl/src/symbol/check_max_angle.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/check_max_angle'>;
}
declare module 'mapbox-gl/src/symbol/clip_line.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/clip_line'>;
}
declare module 'mapbox-gl/src/symbol/collision_box.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/collision_box'>;
}
declare module 'mapbox-gl/src/symbol/collision_feature.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/collision_feature'>;
}
declare module 'mapbox-gl/src/symbol/collision_tile.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/collision_tile'>;
}
declare module 'mapbox-gl/src/symbol/get_anchors.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/get_anchors'>;
}
declare module 'mapbox-gl/src/symbol/glyph_atlas.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/glyph_atlas'>;
}
declare module 'mapbox-gl/src/symbol/glyph_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/glyph_source'>;
}
declare module 'mapbox-gl/src/symbol/mergelines.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/mergelines'>;
}
declare module 'mapbox-gl/src/symbol/quads.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/quads'>;
}
declare module 'mapbox-gl/src/symbol/shaping.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/shaping'>;
}
declare module 'mapbox-gl/src/symbol/sprite_atlas.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/sprite_atlas'>;
}
declare module 'mapbox-gl/src/symbol/transform_text.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/transform_text'>;
}
declare module 'mapbox-gl/src/ui/bind_handlers.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/bind_handlers'>;
}
declare module 'mapbox-gl/src/ui/camera.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/camera'>;
}
declare module 'mapbox-gl/src/ui/control/attribution_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/attribution_control'>;
}
declare module 'mapbox-gl/src/ui/control/fullscreen_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/fullscreen_control'>;
}
declare module 'mapbox-gl/src/ui/control/geolocate_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/geolocate_control'>;
}
declare module 'mapbox-gl/src/ui/control/logo_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/logo_control'>;
}
declare module 'mapbox-gl/src/ui/control/navigation_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/navigation_control'>;
}
declare module 'mapbox-gl/src/ui/control/scale_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/scale_control'>;
}
declare module 'mapbox-gl/src/ui/handler/box_zoom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/box_zoom'>;
}
declare module 'mapbox-gl/src/ui/handler/dblclick_zoom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/dblclick_zoom'>;
}
declare module 'mapbox-gl/src/ui/handler/drag_pan.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/drag_pan'>;
}
declare module 'mapbox-gl/src/ui/handler/drag_rotate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/drag_rotate'>;
}
declare module 'mapbox-gl/src/ui/handler/keyboard.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/keyboard'>;
}
declare module 'mapbox-gl/src/ui/handler/scroll_zoom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/scroll_zoom'>;
}
declare module 'mapbox-gl/src/ui/handler/touch_zoom_rotate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/touch_zoom_rotate'>;
}
declare module 'mapbox-gl/src/ui/hash.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/hash'>;
}
declare module 'mapbox-gl/src/ui/map.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/map'>;
}
declare module 'mapbox-gl/src/ui/marker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/marker'>;
}
declare module 'mapbox-gl/src/ui/popup.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/popup'>;
}
declare module 'mapbox-gl/src/util/actor.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/actor'>;
}
declare module 'mapbox-gl/src/util/ajax.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/ajax'>;
}
declare module 'mapbox-gl/src/util/browser.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/browser'>;
}
declare module 'mapbox-gl/src/util/browser/web_worker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/browser/web_worker'>;
}
declare module 'mapbox-gl/src/util/browser/window.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/browser/window'>;
}
declare module 'mapbox-gl/src/util/classify_rings.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/classify_rings'>;
}
declare module 'mapbox-gl/src/util/config.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/config'>;
}
declare module 'mapbox-gl/src/util/dictionary_coder.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/dictionary_coder'>;
}
declare module 'mapbox-gl/src/util/dispatcher.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/dispatcher'>;
}
declare module 'mapbox-gl/src/util/dom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/dom'>;
}
declare module 'mapbox-gl/src/util/evented.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/evented'>;
}
declare module 'mapbox-gl/src/util/find_pole_of_inaccessibility.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/find_pole_of_inaccessibility'>;
}
declare module 'mapbox-gl/src/util/global_worker_pool.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/global_worker_pool'>;
}
declare module 'mapbox-gl/src/util/glyphs.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/glyphs'>;
}
declare module 'mapbox-gl/src/util/intersection_tests.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/intersection_tests'>;
}
declare module 'mapbox-gl/src/util/is_char_in_unicode_block.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/is_char_in_unicode_block'>;
}
declare module 'mapbox-gl/src/util/lru_cache.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/lru_cache'>;
}
declare module 'mapbox-gl/src/util/mapbox.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/mapbox'>;
}
declare module 'mapbox-gl/src/util/script_detection.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/script_detection'>;
}
declare module 'mapbox-gl/src/util/smart_wrap.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/smart_wrap'>;
}
declare module 'mapbox-gl/src/util/struct_array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/struct_array'>;
}
declare module 'mapbox-gl/src/util/token.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/token'>;
}
declare module 'mapbox-gl/src/util/util.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/util'>;
}
declare module 'mapbox-gl/src/util/vectortile_to_geojson.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/vectortile_to_geojson'>;
}
declare module 'mapbox-gl/src/util/verticalize_punctuation.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/verticalize_punctuation'>;
}
declare module 'mapbox-gl/src/util/web_worker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/web_worker'>;
}
declare module 'mapbox-gl/src/util/window.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/window'>;
}
declare module 'mapbox-gl/src/util/worker_pool.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/worker_pool'>;
}
