// flow-typed signature: eb5aef29afac5d644471e80989739475
// flow-typed version: <<STUB>>/mapbox-gl_v^0.36.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapbox-gl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapbox-gl/dist/mapbox-gl-dev' {
  declare module.exports: any;
}

declare module 'mapbox-gl/dist/mapbox-gl' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-interfaces/mapbox-gl-js-test' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-interfaces/point-geometry' {
  declare module.exports: any;
}

declare module 'mapbox-gl/flow-interfaces/unitbezier' {
  declare module.exports: any;
}

declare module 'mapbox-gl/plugins/src/mapbox-gl-directions/v3.1.1/mapbox-gl-directions' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/array_group' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/circle_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/fill_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/fill_extrusion_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/line_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/bucket/symbol_bucket' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/buffer_group' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/buffer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/element_array_type' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/extent' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/feature_index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/load_geometry' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/pos_array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/program_configuration' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/raster_bounds_array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/data/vertex_array_type' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/coordinate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/lng_lat_bounds' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/lng_lat' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/geo/transform' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_background' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_circle' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_collision_debug' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_debug' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_fill_extrusion' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_fill' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_line' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_raster' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/draw_symbol' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/frame_history' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/line_atlas' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/painter' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/pattern' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/shaders' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/render/vertex_array_object' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/shaders/encode_attribute' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/canvas_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/geojson_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/geojson_worker_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/geojson_wrapper' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/image_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/load_tilejson' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/pixels_to_tile_units' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/query_features' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/raster_tile_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/rtl_text_plugin' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/source_cache' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/tile_bounds' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/tile_coord' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/tile' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/vector_tile_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/vector_tile_worker_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/video_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/worker_tile' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/source/worker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/composite' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/declass' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/deref' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/diff' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/error/parsing_error' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/error/validation_error' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/feature_filter/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/format' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/function/color_spaces' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/function/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/group_by_layout' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate/v7' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate/v8' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/migrate/v9' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/minifyify_style_spec' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/ansi-styles/ansi-styles' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/chalk/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/csscolorparser/csscolorparser' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/fixtures/final-boss-undefined' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/fixtures/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/test/fastest' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/test/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/test/valid' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/util/eachRecursive' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/has-color/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/lib/cli' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/lib/formatter' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/lib/jsonlint' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/scripts/bundle' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/test/all-tests' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/web/json2' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/web/jsonlint' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Chain' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Dumper' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Hash' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Link' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Namespace' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Opt' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Reflection' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/String' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Testrun' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/FOODOC' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC/DomReader' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC/XMLDoc' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC/XMLParse' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/DocComment' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/DocTag' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/JsDoc' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/JsPlate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Lang' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Parser' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/PluginManager' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Symbol' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/SymbolSet' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/TextStream' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Token' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/TokenReader' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/TokenStream' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Util' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Walker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/main' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/commentSrcJson' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/frameworkPrototype' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/functionCall' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/publishSrcHilite' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/symbolLink' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/tagParamConfig' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/tagSynonyms' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/run' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/t/runner' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/t/TestDoc' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/addon' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/anon_inner' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/augments' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/augments2' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/borrows' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/borrows2' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/config' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/constructs' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/encoding_other' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/encoding' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/event' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/exports' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/functions_anon' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/functions_nested' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/global' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/globals' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/ignore' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/inner' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/jsdoc_test' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/lend' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof_constructor' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof2' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof3' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/module' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/multi_methods' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/name' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/namespace_nested' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/nocode' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/oblit_anon' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/overview' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/param_inline' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/params_optional' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype_nested' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype_oblit_constructor' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype_oblit' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/public' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/scripts/code' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/shared' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/shared2' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/shortcuts' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/static_this' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/synonyms' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/tosource' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/variable_redefine' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/bluelabel/publish' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/codeview/javascript/wbos.csstools.mediaqueryfallback' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/codeview/publish' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/jsdoc/publish' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/environments' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/json-schema-draft-01' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/json-schema-draft-02' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/json-schema-draft-03' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/jsv' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/uri/schemes/urn' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/uri/uri' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/tests/qunit' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/tests/tests' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/tests/tests3' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/JSV/tests/tests3b' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/lodash._baseisequal/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/lodash._bindcallback/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/lodash._getnative/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/lodash.isarguments/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/lodash.isarray/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/lodash.isequal/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/lodash.istypedarray/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/lodash.keys/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/minimist/example/parse' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/minimist/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/dash' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/default_bool' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/dotted' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/long' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/parse_modified' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/parse' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/short' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/whitespace' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/nomnom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/callback' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/commands' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/expected' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/matching' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/option' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/transform' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/usage' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/values' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/rw/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/dash' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/decode' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/encode' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/read-file-sync' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/read-file' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/write-file-sync' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/write-file' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/sort-asc/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/sort-asc/test' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/sort-desc/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/sort-desc/test' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/sort-object/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/sort-object/test' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/strip-ansi/cli' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/strip-ansi/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/underscore/underscore-min' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/node_modules/underscore/underscore' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/reference/latest' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/extend' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/get_type' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/interpolate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/parse_color' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/ref_properties' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/util/unbundle_jsonlint' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate_style' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate_style.min' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/latest' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_boolean' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_color' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_constants' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_enum' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_filter' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_function' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_glyphs_url' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_layout_property' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_light' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_number' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_object' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_paint_property' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_property' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate_string' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style-spec/validate/validate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/animation_loop' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/image_sprite' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/light' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_declaration' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer_index' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/circle_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/fill_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/line_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_layer/symbol_style_layer' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style_transition' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/style' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/style/validate_style' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/anchor' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/check_max_angle' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/clip_line' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/collision_box' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/collision_feature' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/collision_tile' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/get_anchors' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/glyph_atlas' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/glyph_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/mergelines' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/quads' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/shaping' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/sprite_atlas' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/symbol/transform_text' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/bind_handlers' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/camera' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/attribution_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/fullscreen_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/geolocate_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/logo_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/navigation_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/control/scale_control' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/box_zoom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/dblclick_zoom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/drag_pan' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/drag_rotate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/keyboard' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/scroll_zoom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/handler/touch_zoom_rotate' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/hash' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/map' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/marker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/ui/popup' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/actor' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/ajax' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/browser' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/browser/web_worker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/browser/window' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/classify_rings' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/config' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/dictionary_coder' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/dispatcher' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/dom' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/evented' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/find_pole_of_inaccessibility' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/global_worker_pool' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/glyphs' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/intersection_tests' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/is_char_in_unicode_block' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/lru_cache' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/mapbox' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/script_detection' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/struct_array' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/token' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/util' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/vectortile_to_geojson' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/verticalize_punctuation' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/web_worker' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/window' {
  declare module.exports: any;
}

declare module 'mapbox-gl/src/util/worker_pool' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapbox-gl/dist/mapbox-gl-dev.js' {
  declare module.exports: $Exports<'mapbox-gl/dist/mapbox-gl-dev'>;
}
declare module 'mapbox-gl/dist/mapbox-gl.js' {
  declare module.exports: $Exports<'mapbox-gl/dist/mapbox-gl'>;
}
declare module 'mapbox-gl/flow-interfaces/mapbox-gl-js-test.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-interfaces/mapbox-gl-js-test'>;
}
declare module 'mapbox-gl/flow-interfaces/point-geometry.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-interfaces/point-geometry'>;
}
declare module 'mapbox-gl/flow-interfaces/unitbezier.js' {
  declare module.exports: $Exports<'mapbox-gl/flow-interfaces/unitbezier'>;
}
declare module 'mapbox-gl/plugins/src/mapbox-gl-directions/v3.1.1/mapbox-gl-directions.js' {
  declare module.exports: $Exports<'mapbox-gl/plugins/src/mapbox-gl-directions/v3.1.1/mapbox-gl-directions'>;
}
declare module 'mapbox-gl/src/data/array_group.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/array_group'>;
}
declare module 'mapbox-gl/src/data/bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/circle_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/circle_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/fill_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/fill_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/fill_extrusion_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/fill_extrusion_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/line_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/line_bucket'>;
}
declare module 'mapbox-gl/src/data/bucket/symbol_bucket.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/bucket/symbol_bucket'>;
}
declare module 'mapbox-gl/src/data/buffer_group.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/buffer_group'>;
}
declare module 'mapbox-gl/src/data/buffer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/buffer'>;
}
declare module 'mapbox-gl/src/data/element_array_type.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/element_array_type'>;
}
declare module 'mapbox-gl/src/data/extent.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/extent'>;
}
declare module 'mapbox-gl/src/data/feature_index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/feature_index'>;
}
declare module 'mapbox-gl/src/data/load_geometry.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/load_geometry'>;
}
declare module 'mapbox-gl/src/data/pos_array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/pos_array'>;
}
declare module 'mapbox-gl/src/data/program_configuration.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/program_configuration'>;
}
declare module 'mapbox-gl/src/data/raster_bounds_array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/raster_bounds_array'>;
}
declare module 'mapbox-gl/src/data/vertex_array_type.js' {
  declare module.exports: $Exports<'mapbox-gl/src/data/vertex_array_type'>;
}
declare module 'mapbox-gl/src/geo/coordinate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/coordinate'>;
}
declare module 'mapbox-gl/src/geo/lng_lat_bounds.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/lng_lat_bounds'>;
}
declare module 'mapbox-gl/src/geo/lng_lat.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/lng_lat'>;
}
declare module 'mapbox-gl/src/geo/transform.js' {
  declare module.exports: $Exports<'mapbox-gl/src/geo/transform'>;
}
declare module 'mapbox-gl/src/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/index'>;
}
declare module 'mapbox-gl/src/render/draw_background.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_background'>;
}
declare module 'mapbox-gl/src/render/draw_circle.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_circle'>;
}
declare module 'mapbox-gl/src/render/draw_collision_debug.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_collision_debug'>;
}
declare module 'mapbox-gl/src/render/draw_debug.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_debug'>;
}
declare module 'mapbox-gl/src/render/draw_fill_extrusion.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_fill_extrusion'>;
}
declare module 'mapbox-gl/src/render/draw_fill.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_fill'>;
}
declare module 'mapbox-gl/src/render/draw_line.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_line'>;
}
declare module 'mapbox-gl/src/render/draw_raster.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_raster'>;
}
declare module 'mapbox-gl/src/render/draw_symbol.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/draw_symbol'>;
}
declare module 'mapbox-gl/src/render/frame_history.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/frame_history'>;
}
declare module 'mapbox-gl/src/render/line_atlas.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/line_atlas'>;
}
declare module 'mapbox-gl/src/render/painter.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/painter'>;
}
declare module 'mapbox-gl/src/render/pattern.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/pattern'>;
}
declare module 'mapbox-gl/src/render/shaders.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/shaders'>;
}
declare module 'mapbox-gl/src/render/vertex_array_object.js' {
  declare module.exports: $Exports<'mapbox-gl/src/render/vertex_array_object'>;
}
declare module 'mapbox-gl/src/shaders/encode_attribute.js' {
  declare module.exports: $Exports<'mapbox-gl/src/shaders/encode_attribute'>;
}
declare module 'mapbox-gl/src/source/canvas_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/canvas_source'>;
}
declare module 'mapbox-gl/src/source/geojson_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/geojson_source'>;
}
declare module 'mapbox-gl/src/source/geojson_worker_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/geojson_worker_source'>;
}
declare module 'mapbox-gl/src/source/geojson_wrapper.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/geojson_wrapper'>;
}
declare module 'mapbox-gl/src/source/image_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/image_source'>;
}
declare module 'mapbox-gl/src/source/load_tilejson.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/load_tilejson'>;
}
declare module 'mapbox-gl/src/source/pixels_to_tile_units.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/pixels_to_tile_units'>;
}
declare module 'mapbox-gl/src/source/query_features.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/query_features'>;
}
declare module 'mapbox-gl/src/source/raster_tile_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/raster_tile_source'>;
}
declare module 'mapbox-gl/src/source/rtl_text_plugin.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/rtl_text_plugin'>;
}
declare module 'mapbox-gl/src/source/source_cache.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/source_cache'>;
}
declare module 'mapbox-gl/src/source/source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/source'>;
}
declare module 'mapbox-gl/src/source/tile_bounds.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/tile_bounds'>;
}
declare module 'mapbox-gl/src/source/tile_coord.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/tile_coord'>;
}
declare module 'mapbox-gl/src/source/tile.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/tile'>;
}
declare module 'mapbox-gl/src/source/vector_tile_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/vector_tile_source'>;
}
declare module 'mapbox-gl/src/source/vector_tile_worker_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/vector_tile_worker_source'>;
}
declare module 'mapbox-gl/src/source/video_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/video_source'>;
}
declare module 'mapbox-gl/src/source/worker_tile.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/worker_tile'>;
}
declare module 'mapbox-gl/src/source/worker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/source/worker'>;
}
declare module 'mapbox-gl/src/style-spec/composite.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/composite'>;
}
declare module 'mapbox-gl/src/style-spec/declass.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/declass'>;
}
declare module 'mapbox-gl/src/style-spec/deref.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/deref'>;
}
declare module 'mapbox-gl/src/style-spec/diff.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/diff'>;
}
declare module 'mapbox-gl/src/style-spec/error/parsing_error.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/error/parsing_error'>;
}
declare module 'mapbox-gl/src/style-spec/error/validation_error.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/error/validation_error'>;
}
declare module 'mapbox-gl/src/style-spec/feature_filter/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/feature_filter/index'>;
}
declare module 'mapbox-gl/src/style-spec/format.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/format'>;
}
declare module 'mapbox-gl/src/style-spec/function/color_spaces.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/function/color_spaces'>;
}
declare module 'mapbox-gl/src/style-spec/function/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/function/index'>;
}
declare module 'mapbox-gl/src/style-spec/group_by_layout.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/group_by_layout'>;
}
declare module 'mapbox-gl/src/style-spec/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/index'>;
}
declare module 'mapbox-gl/src/style-spec/migrate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate'>;
}
declare module 'mapbox-gl/src/style-spec/migrate/v7.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate/v7'>;
}
declare module 'mapbox-gl/src/style-spec/migrate/v8.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate/v8'>;
}
declare module 'mapbox-gl/src/style-spec/migrate/v9.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/migrate/v9'>;
}
declare module 'mapbox-gl/src/style-spec/minifyify_style_spec.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/minifyify_style_spec'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/ansi-styles/ansi-styles.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/ansi-styles/ansi-styles'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/chalk/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/chalk/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/csscolorparser/csscolorparser.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/csscolorparser/csscolorparser'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/fixtures/final-boss-undefined.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/fixtures/final-boss-undefined'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/fixtures/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/fixtures/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/test/fastest.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/test/fastest'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/test/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/test/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/test/valid.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/test/valid'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/util/eachRecursive.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/fast-stable-stringify/util/eachRecursive'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/has-color/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/has-color/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/lib/cli.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/lib/cli'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/lib/formatter.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/lib/formatter'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/lib/jsonlint.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/lib/jsonlint'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/scripts/bundle.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/scripts/bundle'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/test/all-tests.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/test/all-tests'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/web/json2.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/web/json2'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/web/jsonlint.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/jsonlint-lines-primitives/web/jsonlint'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Chain.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Chain'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Dumper.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Dumper'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Hash.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Hash'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Link.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Link'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Namespace.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Namespace'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Opt.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Opt'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Reflection.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Reflection'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/String.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/String'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Testrun.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/frame/Testrun'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/FOODOC.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/FOODOC'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC/DomReader.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC/DomReader'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC/XMLDoc.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC/XMLDoc'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC/XMLParse.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/handlers/XMLDOC/XMLParse'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/DocComment.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/DocComment'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/DocTag.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/DocTag'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/JsDoc.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/JsDoc'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/JsPlate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/JsPlate'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Lang.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Lang'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Parser.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Parser'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/PluginManager.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/PluginManager'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Symbol.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Symbol'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/SymbolSet.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/SymbolSet'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/TextStream.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/TextStream'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Token.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Token'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/TokenReader.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/TokenReader'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/TokenStream.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/TokenStream'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Util.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Util'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Walker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/lib/JSDOC/Walker'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/main.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/main'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/commentSrcJson.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/commentSrcJson'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/frameworkPrototype.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/frameworkPrototype'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/functionCall.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/functionCall'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/publishSrcHilite.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/publishSrcHilite'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/symbolLink.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/symbolLink'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/tagParamConfig.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/tagParamConfig'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/tagSynonyms.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/plugins/tagSynonyms'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/run.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/run'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/t/runner.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/t/runner'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/t/TestDoc.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/t/TestDoc'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/addon.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/addon'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/anon_inner.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/anon_inner'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/augments.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/augments'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/augments2.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/augments2'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/borrows.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/borrows'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/borrows2.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/borrows2'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/config.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/config'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/constructs.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/constructs'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/encoding_other.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/encoding_other'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/encoding.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/encoding'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/event.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/event'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/exports.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/exports'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/functions_anon.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/functions_anon'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/functions_nested.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/functions_nested'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/global.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/global'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/globals.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/globals'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/ignore.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/ignore'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/inner.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/inner'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/jsdoc_test.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/jsdoc_test'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/lend.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/lend'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof_constructor.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof_constructor'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof2.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof2'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof3.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/memberof3'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/module.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/module'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/multi_methods.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/multi_methods'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/name.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/name'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/namespace_nested.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/namespace_nested'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/nocode.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/nocode'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/oblit_anon.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/oblit_anon'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/overview.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/overview'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/param_inline.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/param_inline'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/params_optional.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/params_optional'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype_nested.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype_nested'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype_oblit_constructor.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype_oblit_constructor'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype_oblit.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype_oblit'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/prototype'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/public.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/public'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/scripts/code.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/scripts/code'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/shared.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/shared'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/shared2.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/shared2'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/shortcuts.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/shortcuts'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/static_this.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/static_this'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/synonyms.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/synonyms'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/tosource.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/tosource'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/variable_redefine.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/app/test/variable_redefine'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/bluelabel/publish.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/bluelabel/publish'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/codeview/javascript/wbos.csstools.mediaqueryfallback.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/codeview/javascript/wbos.csstools.mediaqueryfallback'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/codeview/publish.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/codeview/publish'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/jsdoc/publish.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/jsdoc-toolkit/templates/jsdoc/publish'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/environments.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/lib/environments'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/json-schema-draft-01.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/lib/json-schema-draft-01'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/json-schema-draft-02.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/lib/json-schema-draft-02'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/json-schema-draft-03.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/lib/json-schema-draft-03'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/jsv.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/lib/jsv'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/uri/schemes/urn.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/lib/uri/schemes/urn'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/lib/uri/uri.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/lib/uri/uri'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/tests/qunit.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/tests/qunit'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/tests/tests.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/tests/tests'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/tests/tests3.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/tests/tests3'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/JSV/tests/tests3b.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/JSV/tests/tests3b'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/lodash._baseisequal/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/lodash._baseisequal/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/lodash._bindcallback/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/lodash._bindcallback/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/lodash._getnative/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/lodash._getnative/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/lodash.isarguments/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/lodash.isarguments/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/lodash.isarray/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/lodash.isarray/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/lodash.isequal/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/lodash.isequal/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/lodash.istypedarray/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/lodash.istypedarray/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/lodash.keys/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/lodash.keys/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/minimist/example/parse.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/minimist/example/parse'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/minimist/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/minimist/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/dash.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/minimist/test/dash'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/default_bool.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/minimist/test/default_bool'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/dotted.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/minimist/test/dotted'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/long.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/minimist/test/long'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/parse_modified.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/minimist/test/parse_modified'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/parse.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/minimist/test/parse'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/short.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/minimist/test/short'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/minimist/test/whitespace.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/minimist/test/whitespace'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/nomnom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/nomnom/nomnom'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/nomnom/test'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/callback.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/nomnom/test/callback'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/commands.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/nomnom/test/commands'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/expected.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/nomnom/test/expected'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/matching.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/nomnom/test/matching'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/option.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/nomnom/test/option'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/transform.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/nomnom/test/transform'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/usage.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/nomnom/test/usage'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/nomnom/test/values.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/nomnom/test/values'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/rw/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/rw/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/dash.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/dash'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/decode.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/decode'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/encode.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/encode'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/read-file-sync.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/read-file-sync'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/read-file.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/read-file'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/write-file-sync.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/write-file-sync'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/write-file.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/rw/lib/rw/write-file'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/sort-asc/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/sort-asc/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/sort-asc/test.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/sort-asc/test'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/sort-desc/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/sort-desc/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/sort-desc/test.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/sort-desc/test'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/sort-object/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/sort-object/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/sort-object/test.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/sort-object/test'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/strip-ansi/cli.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/strip-ansi/cli'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/strip-ansi/index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/strip-ansi/index'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/underscore/underscore-min.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/underscore/underscore-min'>;
}
declare module 'mapbox-gl/src/style-spec/node_modules/underscore/underscore.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/node_modules/underscore/underscore'>;
}
declare module 'mapbox-gl/src/style-spec/reference/latest.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/reference/latest'>;
}
declare module 'mapbox-gl/src/style-spec/util/extend.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/extend'>;
}
declare module 'mapbox-gl/src/style-spec/util/get_type.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/get_type'>;
}
declare module 'mapbox-gl/src/style-spec/util/interpolate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/interpolate'>;
}
declare module 'mapbox-gl/src/style-spec/util/parse_color.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/parse_color'>;
}
declare module 'mapbox-gl/src/style-spec/util/ref_properties.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/ref_properties'>;
}
declare module 'mapbox-gl/src/style-spec/util/unbundle_jsonlint.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/util/unbundle_jsonlint'>;
}
declare module 'mapbox-gl/src/style-spec/validate_style.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate_style'>;
}
declare module 'mapbox-gl/src/style-spec/validate_style.min.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate_style.min'>;
}
declare module 'mapbox-gl/src/style-spec/validate/latest.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/latest'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_array'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_boolean.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_boolean'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_color.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_color'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_constants.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_constants'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_enum.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_enum'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_filter.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_filter'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_function.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_function'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_glyphs_url.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_glyphs_url'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_layer'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_layout_property.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_layout_property'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_light.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_light'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_number.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_number'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_object.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_object'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_paint_property.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_paint_property'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_property.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_property'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_source'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate_string.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate_string'>;
}
declare module 'mapbox-gl/src/style-spec/validate/validate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style-spec/validate/validate'>;
}
declare module 'mapbox-gl/src/style/animation_loop.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/animation_loop'>;
}
declare module 'mapbox-gl/src/style/image_sprite.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/image_sprite'>;
}
declare module 'mapbox-gl/src/style/light.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/light'>;
}
declare module 'mapbox-gl/src/style/style_declaration.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_declaration'>;
}
declare module 'mapbox-gl/src/style/style_layer_index.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer_index'>;
}
declare module 'mapbox-gl/src/style/style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/circle_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/circle_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/fill_extrusion_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/fill_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/fill_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/line_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/line_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_layer/symbol_style_layer.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_layer/symbol_style_layer'>;
}
declare module 'mapbox-gl/src/style/style_transition.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style_transition'>;
}
declare module 'mapbox-gl/src/style/style.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/style'>;
}
declare module 'mapbox-gl/src/style/validate_style.js' {
  declare module.exports: $Exports<'mapbox-gl/src/style/validate_style'>;
}
declare module 'mapbox-gl/src/symbol/anchor.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/anchor'>;
}
declare module 'mapbox-gl/src/symbol/check_max_angle.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/check_max_angle'>;
}
declare module 'mapbox-gl/src/symbol/clip_line.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/clip_line'>;
}
declare module 'mapbox-gl/src/symbol/collision_box.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/collision_box'>;
}
declare module 'mapbox-gl/src/symbol/collision_feature.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/collision_feature'>;
}
declare module 'mapbox-gl/src/symbol/collision_tile.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/collision_tile'>;
}
declare module 'mapbox-gl/src/symbol/get_anchors.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/get_anchors'>;
}
declare module 'mapbox-gl/src/symbol/glyph_atlas.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/glyph_atlas'>;
}
declare module 'mapbox-gl/src/symbol/glyph_source.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/glyph_source'>;
}
declare module 'mapbox-gl/src/symbol/mergelines.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/mergelines'>;
}
declare module 'mapbox-gl/src/symbol/quads.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/quads'>;
}
declare module 'mapbox-gl/src/symbol/shaping.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/shaping'>;
}
declare module 'mapbox-gl/src/symbol/sprite_atlas.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/sprite_atlas'>;
}
declare module 'mapbox-gl/src/symbol/transform_text.js' {
  declare module.exports: $Exports<'mapbox-gl/src/symbol/transform_text'>;
}
declare module 'mapbox-gl/src/ui/bind_handlers.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/bind_handlers'>;
}
declare module 'mapbox-gl/src/ui/camera.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/camera'>;
}
declare module 'mapbox-gl/src/ui/control/attribution_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/attribution_control'>;
}
declare module 'mapbox-gl/src/ui/control/fullscreen_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/fullscreen_control'>;
}
declare module 'mapbox-gl/src/ui/control/geolocate_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/geolocate_control'>;
}
declare module 'mapbox-gl/src/ui/control/logo_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/logo_control'>;
}
declare module 'mapbox-gl/src/ui/control/navigation_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/navigation_control'>;
}
declare module 'mapbox-gl/src/ui/control/scale_control.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/control/scale_control'>;
}
declare module 'mapbox-gl/src/ui/handler/box_zoom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/box_zoom'>;
}
declare module 'mapbox-gl/src/ui/handler/dblclick_zoom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/dblclick_zoom'>;
}
declare module 'mapbox-gl/src/ui/handler/drag_pan.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/drag_pan'>;
}
declare module 'mapbox-gl/src/ui/handler/drag_rotate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/drag_rotate'>;
}
declare module 'mapbox-gl/src/ui/handler/keyboard.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/keyboard'>;
}
declare module 'mapbox-gl/src/ui/handler/scroll_zoom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/scroll_zoom'>;
}
declare module 'mapbox-gl/src/ui/handler/touch_zoom_rotate.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/handler/touch_zoom_rotate'>;
}
declare module 'mapbox-gl/src/ui/hash.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/hash'>;
}
declare module 'mapbox-gl/src/ui/map.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/map'>;
}
declare module 'mapbox-gl/src/ui/marker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/marker'>;
}
declare module 'mapbox-gl/src/ui/popup.js' {
  declare module.exports: $Exports<'mapbox-gl/src/ui/popup'>;
}
declare module 'mapbox-gl/src/util/actor.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/actor'>;
}
declare module 'mapbox-gl/src/util/ajax.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/ajax'>;
}
declare module 'mapbox-gl/src/util/browser.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/browser'>;
}
declare module 'mapbox-gl/src/util/browser/web_worker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/browser/web_worker'>;
}
declare module 'mapbox-gl/src/util/browser/window.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/browser/window'>;
}
declare module 'mapbox-gl/src/util/classify_rings.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/classify_rings'>;
}
declare module 'mapbox-gl/src/util/config.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/config'>;
}
declare module 'mapbox-gl/src/util/dictionary_coder.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/dictionary_coder'>;
}
declare module 'mapbox-gl/src/util/dispatcher.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/dispatcher'>;
}
declare module 'mapbox-gl/src/util/dom.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/dom'>;
}
declare module 'mapbox-gl/src/util/evented.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/evented'>;
}
declare module 'mapbox-gl/src/util/find_pole_of_inaccessibility.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/find_pole_of_inaccessibility'>;
}
declare module 'mapbox-gl/src/util/global_worker_pool.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/global_worker_pool'>;
}
declare module 'mapbox-gl/src/util/glyphs.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/glyphs'>;
}
declare module 'mapbox-gl/src/util/intersection_tests.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/intersection_tests'>;
}
declare module 'mapbox-gl/src/util/is_char_in_unicode_block.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/is_char_in_unicode_block'>;
}
declare module 'mapbox-gl/src/util/lru_cache.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/lru_cache'>;
}
declare module 'mapbox-gl/src/util/mapbox.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/mapbox'>;
}
declare module 'mapbox-gl/src/util/script_detection.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/script_detection'>;
}
declare module 'mapbox-gl/src/util/struct_array.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/struct_array'>;
}
declare module 'mapbox-gl/src/util/token.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/token'>;
}
declare module 'mapbox-gl/src/util/util.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/util'>;
}
declare module 'mapbox-gl/src/util/vectortile_to_geojson.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/vectortile_to_geojson'>;
}
declare module 'mapbox-gl/src/util/verticalize_punctuation.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/verticalize_punctuation'>;
}
declare module 'mapbox-gl/src/util/web_worker.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/web_worker'>;
}
declare module 'mapbox-gl/src/util/window.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/window'>;
}
declare module 'mapbox-gl/src/util/worker_pool.js' {
  declare module.exports: $Exports<'mapbox-gl/src/util/worker_pool'>;
}
