// flow-typed signature: d9cf623901e26092e2549cce2183d0d7
// flow-typed version: <<STUB>>/react-if_v^2.2.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-if'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-if' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-if/lib/ReactIf' {
  declare module.exports: any;
}

declare module 'react-if/test/ReactIf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-if/lib/ReactIf.js' {
  declare module.exports: $Exports<'react-if/lib/ReactIf'>;
}
declare module 'react-if/test/ReactIf.js' {
  declare module.exports: $Exports<'react-if/test/ReactIf'>;
}
