// flow-typed signature: 6c9ff59d72e6d2ece94605b586c5d5e3
// flow-typed version: <<STUB>>/react-mapbox-gl_v^1.3.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mapbox-gl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mapbox-gl/lib/cluster' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/constants/css' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/feature' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/geojson-layer' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/index' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/layer' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/map' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/marker' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/popup' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/projected-layer' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/scale-control' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/source' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/classname' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/diff' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/inject-css' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/overlays' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/types' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/uid' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/zoom-control' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mapbox-gl/lib/cluster.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/cluster'>;
}
declare module 'react-mapbox-gl/lib/constants/css.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/constants/css'>;
}
declare module 'react-mapbox-gl/lib/feature.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/feature'>;
}
declare module 'react-mapbox-gl/lib/geojson-layer.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/geojson-layer'>;
}
declare module 'react-mapbox-gl/lib/index.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/index'>;
}
declare module 'react-mapbox-gl/lib/layer.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/layer'>;
}
declare module 'react-mapbox-gl/lib/map.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/map'>;
}
declare module 'react-mapbox-gl/lib/marker.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/marker'>;
}
declare module 'react-mapbox-gl/lib/popup.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/popup'>;
}
declare module 'react-mapbox-gl/lib/projected-layer.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/projected-layer'>;
}
declare module 'react-mapbox-gl/lib/scale-control.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/scale-control'>;
}
declare module 'react-mapbox-gl/lib/source.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/source'>;
}
declare module 'react-mapbox-gl/lib/util/classname.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/classname'>;
}
declare module 'react-mapbox-gl/lib/util/diff.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/diff'>;
}
declare module 'react-mapbox-gl/lib/util/inject-css.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/inject-css'>;
}
declare module 'react-mapbox-gl/lib/util/overlays.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/overlays'>;
}
declare module 'react-mapbox-gl/lib/util/types.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/types'>;
}
declare module 'react-mapbox-gl/lib/util/uid.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/uid'>;
}
declare module 'react-mapbox-gl/lib/zoom-control.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/zoom-control'>;
}
