// flow-typed signature: 872cac3d61af1f3626af950667ffb34e
// flow-typed version: <<STUB>>/react-native-windows_v^0.52.0-rc.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-windows'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-windows' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-windows/Libraries/Alert/Alert.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ActivityIndicator/ActivityIndicator.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/AppleTV/TVEventHandler.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/Button.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/CheckBox/CheckBox.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/DatePicker/DatePickerIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/DatePickerAndroid/DatePickerAndroid.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/FlipViewWindows/FlipViewWindows.android' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/FlipViewWindows/FlipViewWindows.ios' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/FlipViewWindows/FlipViewWindows.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/FocusableWindows/FocusableWindows.android' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/FocusableWindows/FocusableWindows.ios' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/FocusableWindows/FocusableWindows.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/MaskedViewIOS/MaskedViewIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/Navigation/NavigatorIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/PasswordBoxWindows/PasswordBoxWindows.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/Picker/Picker.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/Picker/PickerAndroid.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/Picker/PickerIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/Picker/PickerWindows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ProgressBarAndroid/ProgressBarAndroid.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ProgressBarWindows/ProgressBarWindows.android' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ProgressBarWindows/ProgressBarWindows.ios' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ProgressBarWindows/ProgressBarWindows.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ProgressRingWindows/ProgressRingWindows.android' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ProgressRingWindows/ProgressRingWindows.ios' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ProgressRingWindows/ProgressRingWindows.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ProgressViewIOS/ProgressViewIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/SafeAreaView/SafeAreaView.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ScrollView/ScrollView.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/SegmentedControlIOS/SegmentedControlIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/SplitViewWindows/SplitViewWindows.android' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/SplitViewWindows/SplitViewWindows.ios' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/SplitViewWindows/SplitViewWindows.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/StatusBar/StatusBar.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/StatusBar/StatusBarIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/TabBarIOS/TabBarIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/TabBarIOS/TabBarItemIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/TextInput/TextInput.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/TextInput/TextInputState.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/TimePickerAndroid/TimePickerAndroid.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ToastAndroid/ToastAndroid.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ToolbarAndroid/ToolbarAndroid.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/Touchable/TouchableNativeFeedback.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/View/ViewPropTypes.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/ViewPager/ViewPagerAndroid.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Components/WebView/WebView.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Core/ReactNativeVersion.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/CustomComponents/NavigationExperimental/NavigationHeaderBackButton.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/CustomComponents/Navigator/NavigatorBreadcrumbNavigationBarStyles.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/CustomComponents/Navigator/NavigatorNavigationBarStylesWindows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Experimental/SwipeableRow/SwipeableRow.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Image/Image.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Network/NetInfo.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Network/RCTNetworking.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/RCTTest/SnapshotViewIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/react-native-windows/react-native-windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Settings/Settings.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Text/Text.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Utilities/BackHandler.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Utilities/HMRLoadingView.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Utilities/Platform.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Vibration/Vibration.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/Vibration/VibrationIOS.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/Libraries/WebSocket/WebSocket.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/generate-windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/generate-wpf' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/generator-utils' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/generator-windows/index' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/generator-windows/templates/App.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/generator-wpf/index' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/generator-wpf/templates/App.windows' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/index' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWindows/runWindows' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWindows/utils/build' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWindows/utils/checkRequirements' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWindows/utils/deploy' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWindows/utils/msbuildtools' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWindows/utils/version' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWindows/utils/winappdeploytool' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWpf/runWpf' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWpf/utils/build' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWpf/utils/checkRequirements' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWpf/utils/deploy' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWpf/utils/msbuildtools' {
  declare module.exports: any;
}

declare module 'react-native-windows/local-cli/runWpf/utils/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-windows/Libraries/Alert/Alert.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Alert/Alert.windows'>;
}
declare module 'react-native-windows/Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/AccessibilityInfo/AccessibilityInfo.windows'>;
}
declare module 'react-native-windows/Libraries/Components/ActivityIndicator/ActivityIndicator.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ActivityIndicator/ActivityIndicator.windows'>;
}
declare module 'react-native-windows/Libraries/Components/AppleTV/TVEventHandler.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/AppleTV/TVEventHandler.windows'>;
}
declare module 'react-native-windows/Libraries/Components/Button.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/Button.windows'>;
}
declare module 'react-native-windows/Libraries/Components/CheckBox/CheckBox.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/CheckBox/CheckBox.windows'>;
}
declare module 'react-native-windows/Libraries/Components/DatePicker/DatePickerIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/DatePicker/DatePickerIOS.windows'>;
}
declare module 'react-native-windows/Libraries/Components/DatePickerAndroid/DatePickerAndroid.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/DatePickerAndroid/DatePickerAndroid.windows'>;
}
declare module 'react-native-windows/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.windows'>;
}
declare module 'react-native-windows/Libraries/Components/FlipViewWindows/FlipViewWindows.android.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/FlipViewWindows/FlipViewWindows.android'>;
}
declare module 'react-native-windows/Libraries/Components/FlipViewWindows/FlipViewWindows.ios.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/FlipViewWindows/FlipViewWindows.ios'>;
}
declare module 'react-native-windows/Libraries/Components/FlipViewWindows/FlipViewWindows.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/FlipViewWindows/FlipViewWindows.windows'>;
}
declare module 'react-native-windows/Libraries/Components/FocusableWindows/FocusableWindows.android.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/FocusableWindows/FocusableWindows.android'>;
}
declare module 'react-native-windows/Libraries/Components/FocusableWindows/FocusableWindows.ios.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/FocusableWindows/FocusableWindows.ios'>;
}
declare module 'react-native-windows/Libraries/Components/FocusableWindows/FocusableWindows.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/FocusableWindows/FocusableWindows.windows'>;
}
declare module 'react-native-windows/Libraries/Components/MaskedViewIOS/MaskedViewIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/MaskedViewIOS/MaskedViewIOS.windows'>;
}
declare module 'react-native-windows/Libraries/Components/Navigation/NavigatorIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/Navigation/NavigatorIOS.windows'>;
}
declare module 'react-native-windows/Libraries/Components/PasswordBoxWindows/PasswordBoxWindows.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/PasswordBoxWindows/PasswordBoxWindows.windows'>;
}
declare module 'react-native-windows/Libraries/Components/Picker/Picker.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/Picker/Picker.windows'>;
}
declare module 'react-native-windows/Libraries/Components/Picker/PickerAndroid.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/Picker/PickerAndroid.windows'>;
}
declare module 'react-native-windows/Libraries/Components/Picker/PickerIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/Picker/PickerIOS.windows'>;
}
declare module 'react-native-windows/Libraries/Components/Picker/PickerWindows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/Picker/PickerWindows'>;
}
declare module 'react-native-windows/Libraries/Components/ProgressBarAndroid/ProgressBarAndroid.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ProgressBarAndroid/ProgressBarAndroid.windows'>;
}
declare module 'react-native-windows/Libraries/Components/ProgressBarWindows/ProgressBarWindows.android.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ProgressBarWindows/ProgressBarWindows.android'>;
}
declare module 'react-native-windows/Libraries/Components/ProgressBarWindows/ProgressBarWindows.ios.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ProgressBarWindows/ProgressBarWindows.ios'>;
}
declare module 'react-native-windows/Libraries/Components/ProgressBarWindows/ProgressBarWindows.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ProgressBarWindows/ProgressBarWindows.windows'>;
}
declare module 'react-native-windows/Libraries/Components/ProgressRingWindows/ProgressRingWindows.android.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ProgressRingWindows/ProgressRingWindows.android'>;
}
declare module 'react-native-windows/Libraries/Components/ProgressRingWindows/ProgressRingWindows.ios.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ProgressRingWindows/ProgressRingWindows.ios'>;
}
declare module 'react-native-windows/Libraries/Components/ProgressRingWindows/ProgressRingWindows.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ProgressRingWindows/ProgressRingWindows.windows'>;
}
declare module 'react-native-windows/Libraries/Components/ProgressViewIOS/ProgressViewIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ProgressViewIOS/ProgressViewIOS.windows'>;
}
declare module 'react-native-windows/Libraries/Components/SafeAreaView/SafeAreaView.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/SafeAreaView/SafeAreaView.windows'>;
}
declare module 'react-native-windows/Libraries/Components/ScrollView/ScrollView.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ScrollView/ScrollView.windows'>;
}
declare module 'react-native-windows/Libraries/Components/SegmentedControlIOS/SegmentedControlIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/SegmentedControlIOS/SegmentedControlIOS.windows'>;
}
declare module 'react-native-windows/Libraries/Components/SplitViewWindows/SplitViewWindows.android.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/SplitViewWindows/SplitViewWindows.android'>;
}
declare module 'react-native-windows/Libraries/Components/SplitViewWindows/SplitViewWindows.ios.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/SplitViewWindows/SplitViewWindows.ios'>;
}
declare module 'react-native-windows/Libraries/Components/SplitViewWindows/SplitViewWindows.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/SplitViewWindows/SplitViewWindows.windows'>;
}
declare module 'react-native-windows/Libraries/Components/StatusBar/StatusBar.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/StatusBar/StatusBar.windows'>;
}
declare module 'react-native-windows/Libraries/Components/StatusBar/StatusBarIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/StatusBar/StatusBarIOS.windows'>;
}
declare module 'react-native-windows/Libraries/Components/TabBarIOS/TabBarIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/TabBarIOS/TabBarIOS.windows'>;
}
declare module 'react-native-windows/Libraries/Components/TabBarIOS/TabBarItemIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/TabBarIOS/TabBarItemIOS.windows'>;
}
declare module 'react-native-windows/Libraries/Components/TextInput/TextInput.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/TextInput/TextInput.windows'>;
}
declare module 'react-native-windows/Libraries/Components/TextInput/TextInputState.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/TextInput/TextInputState.windows'>;
}
declare module 'react-native-windows/Libraries/Components/TimePickerAndroid/TimePickerAndroid.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/TimePickerAndroid/TimePickerAndroid.windows'>;
}
declare module 'react-native-windows/Libraries/Components/ToastAndroid/ToastAndroid.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ToastAndroid/ToastAndroid.windows'>;
}
declare module 'react-native-windows/Libraries/Components/ToolbarAndroid/ToolbarAndroid.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ToolbarAndroid/ToolbarAndroid.windows'>;
}
declare module 'react-native-windows/Libraries/Components/Touchable/TouchableNativeFeedback.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/Touchable/TouchableNativeFeedback.windows'>;
}
declare module 'react-native-windows/Libraries/Components/View/ViewPropTypes.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/View/ViewPropTypes.windows'>;
}
declare module 'react-native-windows/Libraries/Components/ViewPager/ViewPagerAndroid.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/ViewPager/ViewPagerAndroid.windows'>;
}
declare module 'react-native-windows/Libraries/Components/WebView/WebView.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Components/WebView/WebView.windows'>;
}
declare module 'react-native-windows/Libraries/Core/ReactNativeVersion.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Core/ReactNativeVersion.windows'>;
}
declare module 'react-native-windows/Libraries/CustomComponents/NavigationExperimental/NavigationHeaderBackButton.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/CustomComponents/NavigationExperimental/NavigationHeaderBackButton.windows'>;
}
declare module 'react-native-windows/Libraries/CustomComponents/Navigator/NavigatorBreadcrumbNavigationBarStyles.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/CustomComponents/Navigator/NavigatorBreadcrumbNavigationBarStyles.windows'>;
}
declare module 'react-native-windows/Libraries/CustomComponents/Navigator/NavigatorNavigationBarStylesWindows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/CustomComponents/Navigator/NavigatorNavigationBarStylesWindows'>;
}
declare module 'react-native-windows/Libraries/Experimental/SwipeableRow/SwipeableRow.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Experimental/SwipeableRow/SwipeableRow.windows'>;
}
declare module 'react-native-windows/Libraries/Image/Image.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Image/Image.windows'>;
}
declare module 'react-native-windows/Libraries/Network/NetInfo.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Network/NetInfo.windows'>;
}
declare module 'react-native-windows/Libraries/Network/RCTNetworking.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Network/RCTNetworking.windows'>;
}
declare module 'react-native-windows/Libraries/RCTTest/SnapshotViewIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/RCTTest/SnapshotViewIOS.windows'>;
}
declare module 'react-native-windows/Libraries/react-native-windows/react-native-windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/react-native-windows/react-native-windows'>;
}
declare module 'react-native-windows/Libraries/Settings/Settings.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Settings/Settings.windows'>;
}
declare module 'react-native-windows/Libraries/Text/Text.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Text/Text.windows'>;
}
declare module 'react-native-windows/Libraries/Utilities/BackHandler.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Utilities/BackHandler.windows'>;
}
declare module 'react-native-windows/Libraries/Utilities/HMRLoadingView.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Utilities/HMRLoadingView.windows'>;
}
declare module 'react-native-windows/Libraries/Utilities/Platform.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Utilities/Platform.windows'>;
}
declare module 'react-native-windows/Libraries/Vibration/Vibration.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Vibration/Vibration.windows'>;
}
declare module 'react-native-windows/Libraries/Vibration/VibrationIOS.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/Vibration/VibrationIOS.windows'>;
}
declare module 'react-native-windows/Libraries/WebSocket/WebSocket.windows.js' {
  declare module.exports: $Exports<'react-native-windows/Libraries/WebSocket/WebSocket.windows'>;
}
declare module 'react-native-windows/local-cli/generate-windows.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/generate-windows'>;
}
declare module 'react-native-windows/local-cli/generate-wpf.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/generate-wpf'>;
}
declare module 'react-native-windows/local-cli/generator-utils.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/generator-utils'>;
}
declare module 'react-native-windows/local-cli/generator-windows/index.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/generator-windows/index'>;
}
declare module 'react-native-windows/local-cli/generator-windows/templates/App.windows.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/generator-windows/templates/App.windows'>;
}
declare module 'react-native-windows/local-cli/generator-wpf/index.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/generator-wpf/index'>;
}
declare module 'react-native-windows/local-cli/generator-wpf/templates/App.windows.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/generator-wpf/templates/App.windows'>;
}
declare module 'react-native-windows/local-cli/index.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/index'>;
}
declare module 'react-native-windows/local-cli/runWindows/runWindows.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWindows/runWindows'>;
}
declare module 'react-native-windows/local-cli/runWindows/utils/build.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWindows/utils/build'>;
}
declare module 'react-native-windows/local-cli/runWindows/utils/checkRequirements.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWindows/utils/checkRequirements'>;
}
declare module 'react-native-windows/local-cli/runWindows/utils/deploy.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWindows/utils/deploy'>;
}
declare module 'react-native-windows/local-cli/runWindows/utils/msbuildtools.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWindows/utils/msbuildtools'>;
}
declare module 'react-native-windows/local-cli/runWindows/utils/version.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWindows/utils/version'>;
}
declare module 'react-native-windows/local-cli/runWindows/utils/winappdeploytool.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWindows/utils/winappdeploytool'>;
}
declare module 'react-native-windows/local-cli/runWpf/runWpf.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWpf/runWpf'>;
}
declare module 'react-native-windows/local-cli/runWpf/utils/build.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWpf/utils/build'>;
}
declare module 'react-native-windows/local-cli/runWpf/utils/checkRequirements.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWpf/utils/checkRequirements'>;
}
declare module 'react-native-windows/local-cli/runWpf/utils/deploy.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWpf/utils/deploy'>;
}
declare module 'react-native-windows/local-cli/runWpf/utils/msbuildtools.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWpf/utils/msbuildtools'>;
}
declare module 'react-native-windows/local-cli/runWpf/utils/version.js' {
  declare module.exports: $Exports<'react-native-windows/local-cli/runWpf/utils/version'>;
}
