// flow-typed signature: eb83d1f239fcbd0e79bfd75f3b51fc89
// flow-typed version: <<STUB>>/react-custom-scrollbars_v^4.0.2/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-custom-scrollbars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-custom-scrollbars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-custom-scrollbars/dist/react-custom-scrollbars' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/dist/react-custom-scrollbars.min' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/karma.conf' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/lib/index' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/lib/Scrollbars/defaultRenderElements' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/lib/Scrollbars/index' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/lib/Scrollbars/styles' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/lib/utils/getInnerHeight' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/lib/utils/getInnerWidth' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/lib/utils/getScrollbarWidth' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/lib/utils/isString' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/lib/utils/returnFalse' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/prepublish' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/test' {
  declare module.exports: any;
}

declare module 'react-custom-scrollbars/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-custom-scrollbars/dist/react-custom-scrollbars.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/dist/react-custom-scrollbars'>;
}
declare module 'react-custom-scrollbars/dist/react-custom-scrollbars.min.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/dist/react-custom-scrollbars.min'>;
}
declare module 'react-custom-scrollbars/karma.conf.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/karma.conf'>;
}
declare module 'react-custom-scrollbars/lib/index.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/lib/index'>;
}
declare module 'react-custom-scrollbars/lib/Scrollbars/defaultRenderElements.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/lib/Scrollbars/defaultRenderElements'>;
}
declare module 'react-custom-scrollbars/lib/Scrollbars/index.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/lib/Scrollbars/index'>;
}
declare module 'react-custom-scrollbars/lib/Scrollbars/styles.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/lib/Scrollbars/styles'>;
}
declare module 'react-custom-scrollbars/lib/utils/getInnerHeight.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/lib/utils/getInnerHeight'>;
}
declare module 'react-custom-scrollbars/lib/utils/getInnerWidth.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/lib/utils/getInnerWidth'>;
}
declare module 'react-custom-scrollbars/lib/utils/getScrollbarWidth.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/lib/utils/getScrollbarWidth'>;
}
declare module 'react-custom-scrollbars/lib/utils/isString.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/lib/utils/isString'>;
}
declare module 'react-custom-scrollbars/lib/utils/returnFalse.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/lib/utils/returnFalse'>;
}
declare module 'react-custom-scrollbars/prepublish.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/prepublish'>;
}
declare module 'react-custom-scrollbars/test.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/test'>;
}
declare module 'react-custom-scrollbars/webpack.config.js' {
  declare module.exports: $Exports<'react-custom-scrollbars/webpack.config'>;
}
