// flow-typed signature: 9f8752969e81b3c77889d339ee49deb6
// flow-typed version: <<STUB>>/sudo-prompt_v^7.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sudo-prompt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sudo-prompt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sudo-prompt/test-concurrent' {
  declare module.exports: any;
}

declare module 'sudo-prompt/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sudo-prompt/index' {
  declare module.exports: $Exports<'sudo-prompt'>;
}
declare module 'sudo-prompt/index.js' {
  declare module.exports: $Exports<'sudo-prompt'>;
}
declare module 'sudo-prompt/test-concurrent.js' {
  declare module.exports: $Exports<'sudo-prompt/test-concurrent'>;
}
declare module 'sudo-prompt/test.js' {
  declare module.exports: $Exports<'sudo-prompt/test'>;
}
