[target.aarch64-linux-android]
ar = "$NDK_TOOLCHAIN_DIR/aarch64-linux-android-ar"
linker = "$NDK_TOOLCHAIN_DIR/aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
ar = "$NDK_TOOLCHAIN_DIR/arm-linux-androideabi-ar"
linker = "$NDK_TOOLCHAIN_DIR/armv7a-linux-androideabi21-clang"

[target.x86_64-linux-android]
ar = "$NDK_TOOLCHAIN_DIR/x86_64-linux-android-ar"
linker = "$NDK_TOOLCHAIN_DIR/x86_64-linux-android21-clang"

[target.i686-linux-android]
ar = "$NDK_TOOLCHAIN_DIR/i686-linux-android-ar"
linker = "$NDK_TOOLCHAIN_DIR/i686-linux-android21-clang"
