//! Interface with macOS-specific bits.

#![deny(missing_docs)]
#![cfg(target_os = "macos")]

/// Processes
pub mod process;

/// OS bindings generated by 'generate_bindings.rs'
#[expect(non_camel_case_types)]
mod bindings;

/// Networking utilities
pub mod net;
