export enum RoutePath {
  launch = '/',
  login = '/login',
  main = '/main',
  redeemVoucher = '/main/voucher/redeem',
  voucherSuccess = '/main/voucher/success',
  timeAdded = '/main/time-added',
  setupFinished = '/main/setup-finished',
  settings = '/settings',
  selectLanguage = '/settings/language',
  accountSettings = '/settings/account',
  preferences = '/settings/preferences',
  advancedSettings = '/settings/advanced',
  wireguardKeys = '/settings/advanced/wireguard-keys',
  splitTunneling = '/settings/advanced/split-tunneling',
  support = '/settings/support',
  selectLocation = '/select-location',
}
