[package]
name = "tunnel-obfuscation"
edition.workspace = true
rust-version.workspace = true
description = "Provides different types of obfuscation layers for WireGuard"
repository.workspace = true
license.workspace = true

[[bench]]
harness = false
name = "lwo"

[[bench]]
harness = false
name = "obfuscation_throughput"

[[bench]]
harness = false
name = "multiplexer_throughput"

[dependencies]
async-trait = { workspace = true }
blake2 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
mullvad-masque-proxy = { path = "../mullvad-masque-proxy" }
rand = { workspace = true, features = ["small_rng"] }
shadowsocks = { workspace = true }
talpid-net = { path = "../talpid-net" }
talpid-types = { path = "../talpid-types" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "sync"] }
tokio-util = { workspace = true, features = ["rt"] }
udp-over-tcp = { workspace = true }
zerocopy = { workspace = true, features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.7.0", features = ["async_tokio", "html_reports"] }
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
