#!/usr/bin/env bash

set -eu

INSTALL_DIR=$2

# Workaround for issue in electron-builder where the pkg-scripts are run twice, once with the
# correct install dir and once with an incorrect one. This guard prevents running the script when
# called the second time. This can be reverted when the following issue has been fixed:
# https://github.com/electron-userland/electron-builder/issues/8166
if [[ $INSTALL_DIR == *"Mullvad VPN.app" ]]; then
    exit 0
fi

LOG_DIR=/var/log/mullvad-vpn

mkdir -p $LOG_DIR
exec > $LOG_DIR/postinstall.log 2>&1

echo "Running postinstall at $(date)"

# Abort if the "localized" directory exists. This can happen if some other app bundle
# is already occupying the intended target directory, causing macOS to install us in
# /Applications/Mullvad VPN.localized instead. We abort in this case to avoid a potential
# LPE from admin user to root.
if [[ -d "$INSTALL_DIR/Mullvad VPN.localized" ]]; then
    echo "Found '$INSTALL_DIR/Mullvad VPN.localized' unexpectedly. Aborting."
    exit 1
fi

# NOTE: This path must be kept in sync with the path defined
# in mullvad-daemon/src/macos_launch_daemon.rs and preinstall
DAEMON_PLIST_PATH="/Library/LaunchDaemons/net.mullvad.daemon.plist"

# Install the daemon binary to /Library/PrivilegedHelperTools (root:wheel),
# which only root can write to. This prevents admin users from replacing the binary that
# runs as root via the launch daemon.
PRIVILEGED_HELPER_TOOLS_DIR="/Library/PrivilegedHelperTools"
DAEMON_BINARY="$PRIVILEGED_HELPER_TOOLS_DIR/net.mullvad.daemon"

DAEMON_PLIST=$(cat <<-EOM
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
        <dict>
                <key>Label</key>
                <string>net.mullvad.daemon</string>

                <key>ProgramArguments</key>
                <array>
                        <string>$DAEMON_BINARY</string>
                        <string>-v</string>
                </array>

                <key>EnvironmentVariables</key>
                <dict>
                        <key>MULLVAD_RESOURCE_DIR</key>
                        <string>$INSTALL_DIR/Mullvad VPN.app/Contents/Resources</string>
                </dict>

                <key>UserName</key>
                <string>root</string>

                <key>RunAtLoad</key>
                <true/>

                <key>KeepAlive</key>
                <true/>

                <key>SoftResourceLimits</key>
                <dict>
                        <key>NumberOfFiles</key>
                        <integer>1024</integer>
                </dict>

                <key>AssociatedBundleIdentifiers</key>
                <string>net.mullvad.vpn</string>

                <key>StandardErrorPath</key>
                <string>$LOG_DIR/stderr.log</string>
        </dict>
</plist>
EOM
)

# NOTE: We copy `mullvad-daemon` from the app to a directory fully owned by root.
# This may still be exploitable if the app bundle is replaced while postinstall is running.
# But it makes the window a lot smaller.
mkdir -p "$PRIVILEGED_HELPER_TOOLS_DIR"
cp "$INSTALL_DIR/Mullvad VPN.app/Contents/Resources/mullvad-daemon" "$DAEMON_BINARY"
chown root:wheel "$DAEMON_BINARY"
chmod 755 "$DAEMON_BINARY"

ZSH_COMPLETIONS_DIR="/usr/local/share/zsh/site-functions/"

if [[ -d "/opt/homebrew/share/fish/vendor_completions.d/" ]]; then
    FISH_COMPLETIONS_DIR="/opt/homebrew/share/fish/vendor_completions.d/"
else
    FISH_COMPLETIONS_DIR="/usr/local/share/fish/vendor_completions.d/"
fi

cp "$LOG_DIR/daemon.log" "$LOG_DIR/old-install-daemon.log" \
  || echo "Failed to copy old daemon log"

# For compatibility with versions older than 2022.5, kill the GUI after the
# upgrade. We now do this in preinstall instead. This code can be removed when
# we drop support for app versions older than 2022.5.
pkill -x "Mullvad VPN" || true
sleep 1

echo "$DAEMON_PLIST" > $DAEMON_PLIST_PATH
chmod 644 $DAEMON_PLIST_PATH
launchctl load -w $DAEMON_PLIST_PATH

mkdir -p /usr/local/bin
ln -sf "$INSTALL_DIR/Mullvad VPN.app/Contents/Resources/mullvad" /usr/local/bin/mullvad
ln -sf "$INSTALL_DIR/Mullvad VPN.app/Contents/Resources/mullvad-problem-report" /usr/local/bin/mullvad-problem-report

mkdir -p "$ZSH_COMPLETIONS_DIR"
ln -sf "$INSTALL_DIR/Mullvad VPN.app/Contents/Resources/_mullvad" "$ZSH_COMPLETIONS_DIR/_mullvad"

if [[ -d "$FISH_COMPLETIONS_DIR" ]]; then
    ln -sf "$INSTALL_DIR/Mullvad VPN.app/Contents/Resources/mullvad.fish" "$FISH_COMPLETIONS_DIR/mullvad.fish"
fi
