package net.mullvad.mullvadvpn.model

import android.os.Parcelable
import kotlinx.parcelize.IgnoredOnParcel
import kotlinx.parcelize.Parcelize
import net.mullvad.mullvadvpn.util.parseAsDateTime

@Parcelize
data class Device(
    val id: String,
    val name: String,
    val pubkey: ByteArray,
    val ports: ArrayList<DevicePort>,
    val created: String
) : Parcelable {

    @IgnoredOnParcel
    val creationDate by lazy { created.parseAsDateTime() }

    // Generated by Android Studio
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Device

        if (id != other.id) return false
        if (name != other.name) return false
        if (!pubkey.contentEquals(other.pubkey)) return false
        if (ports != other.ports) return false

        return true
    }

    // Generated by Android Studio
    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + name.hashCode()
        result = 31 * result + pubkey.contentHashCode()
        result = 31 * result + ports.hashCode()
        return result
    }
}
