//! A userspace IP networking stack built on smoltcp, providing TCP and ICMP
//! sockets whose traffic is surfaced as gotatun [`IpSend`]/[`IpRecv`] streams.
//!
//! This is used on iOS where the tunnel process cannot bind sockets to the
//! tunnel device directly. Instead, smoltcp generates raw IP packets that are
//! fed into a GotaTun device via [`IpRecv`], and decrypted return traffic is
//! fed back via [`IpSend`].

mod device;

use bytes::BytesMut;
use device::SmoltcpDevice;
use gotatun::{
    packet::{Ip, Packet, PacketBufPool},
    tun::{IpRecv, IpSend, MtuWatcher},
};
use smoltcp::{
    iface::{Config as IfaceConfig, Interface, SocketHandle, SocketSet},
    socket::{icmp, tcp},
    time::Instant as SmoltcpInstant,
    wire::{IpAddress, IpCidr, IpEndpoint, IpListenEndpoint},
};
use std::{
    collections::VecDeque,
    io,
    net::{Ipv4Addr, Ipv6Addr, SocketAddr},
    pin::Pin,
    sync::Arc,
    task::{Context, Poll, ready},
    time::Instant as StdInstant,
};
use tokio::{
    io::{AsyncRead, AsyncWrite, ReadBuf},
    sync::{Notify, mpsc, oneshot},
    task::JoinHandle,
};

/// Channel capacity for packets between SmoltcpNetwork and GotaTun.
const PACKET_CHANNEL_CAPACITY: usize = 256;
/// Channel capacity for TCP data between socket handles and the poll loop.
const TCP_DATA_CHANNEL_CAPACITY: usize = 64;
/// Channel capacity for ICMP between socket handles and the poll loop.
const ICMP_CHANNEL_CAPACITY: usize = 16;
/// Channel capacity for socket commands.
const CMD_CHANNEL_CAPACITY: usize = 16;

/// Size of TCP socket receive and send buffers within smoltcp.
const TCP_BUFFER_SIZE: usize = 65535;
/// Number of ICMP packet metadata slots.
const ICMP_METADATA_SLOTS: usize = 8;
/// Size of ICMP packet buffer.
const ICMP_BUFFER_SIZE: usize = 2048;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// Configuration for creating a [`SmoltcpNetwork`].
pub struct SmoltcpNetworkConfig {
    /// Source IPv4 address for the virtual interface.
    pub ipv4_addr: Ipv4Addr,
    /// Optional source IPv6 address.
    pub ipv6_addr: Option<Ipv6Addr>,
    /// MTU for the virtual interface. Should be `tunnel_mtu - WIREGUARD_HEADER_SIZE`.
    pub mtu: u16,
}

/// A userspace IP networking stack. Owns a background poll loop task.
///
/// When dropped, the poll loop is aborted.
pub struct SmoltcpNetwork {
    /// Handle for creating sockets. Cheaply cloneable.
    pub handle: SmoltcpHandle,
    /// The [`IpRecv`] half — yields packets generated by smoltcp to GotaTun.
    pub ip_recv: SmoltcpIpRecv,
    /// The [`IpSend`] half — receives decrypted return traffic from GotaTun.
    pub ip_send: SmoltcpIpSend,
    poll_task: JoinHandle<()>,
}

impl SmoltcpNetwork {
    /// Create a new smoltcp-based network stack.
    ///
    /// Spawns a background tokio task that drives the smoltcp interface.
    pub fn new(config: SmoltcpNetworkConfig) -> Self {
        let (to_gotatun_tx, to_gotatun_rx) = mpsc::channel(PACKET_CHANNEL_CAPACITY);
        let (from_gotatun_tx, from_gotatun_rx) = mpsc::channel(PACKET_CHANNEL_CAPACITY);
        let (cmd_tx, cmd_rx) = mpsc::channel(CMD_CHANNEL_CAPACITY);
        let notify = Arc::new(Notify::new());

        let mtu_watcher = MtuWatcher::new(config.mtu);

        let ip_recv = SmoltcpIpRecv {
            rx: to_gotatun_rx,
            mtu: mtu_watcher,
        };

        let ip_send = SmoltcpIpSend {
            tx: from_gotatun_tx,
            notify: notify.clone(),
        };

        let handle = SmoltcpHandle {
            cmd_tx,
            notify: notify.clone(),
        };

        let poll_task = tokio::spawn(poll_loop(
            config,
            from_gotatun_rx,
            to_gotatun_tx,
            cmd_rx,
            notify,
        ));

        Self {
            handle,
            ip_recv,
            ip_send,
            poll_task,
        }
    }
}

impl SmoltcpNetwork {
    /// Decompose into constituent parts, aborting the poll loop task on drop
    /// of the returned guard.
    pub fn into_parts(
        self,
    ) -> (
        SmoltcpHandle,
        SmoltcpIpRecv,
        SmoltcpIpSend,
        SmoltcpNetworkGuard,
    ) {
        // Use ManuallyDrop to avoid triggering Drop while moving fields out
        let this = std::mem::ManuallyDrop::new(self);
        let handle = this.handle.clone();
        // Safety: we're consuming self, so these fields won't be accessed again
        let ip_recv = unsafe { std::ptr::read(&this.ip_recv) };
        let ip_send = unsafe { std::ptr::read(&this.ip_send) };
        let poll_task = unsafe { std::ptr::read(&this.poll_task) };
        (handle, ip_recv, ip_send, SmoltcpNetworkGuard { poll_task })
    }
}

/// Guard that aborts the poll loop task when dropped.
pub struct SmoltcpNetworkGuard {
    poll_task: JoinHandle<()>,
}

impl Drop for SmoltcpNetworkGuard {
    fn drop(&mut self) {
        self.poll_task.abort();
    }
}

impl Drop for SmoltcpNetwork {
    fn drop(&mut self) {
        self.poll_task.abort();
    }
}

/// A cloneable handle for creating sockets on a [`SmoltcpNetwork`].
#[derive(Clone)]
pub struct SmoltcpHandle {
    cmd_tx: mpsc::Sender<SocketCmd>,
    notify: Arc<Notify>,
}

impl SmoltcpHandle {
    /// Open a TCP connection to the given address through the smoltcp stack.
    ///
    /// The returned stream may be used immediately. Reads will pend until the
    /// TCP handshake completes and data arrives. Writes are buffered and
    /// flushed once the connection is established.
    pub async fn tcp_connect(&self, addr: SocketAddr) -> io::Result<SmoltcpTcpStream> {
        let (tx, rx) = oneshot::channel();
        self.cmd_tx
            .send(SocketCmd::TcpConnect { addr, response: tx })
            .await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "poll loop closed"))?;
        self.notify.notify_one();
        rx.await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "poll loop dropped"))?
    }

    /// Create an ICMP socket bound to the given identifier.
    ///
    /// Only ICMP echo replies matching this identifier will be delivered.
    pub async fn icmp_socket(&self, ident: u16) -> io::Result<SmoltcpIcmpSocket> {
        let (tx, rx) = oneshot::channel();
        self.cmd_tx
            .send(SocketCmd::CreateIcmpSocket {
                ident,
                response: tx,
            })
            .await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "poll loop closed"))?;
        self.notify.notify_one();
        rx.await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "poll loop dropped"))?
    }
}

// ---------------------------------------------------------------------------
// IpRecv / IpSend implementations
// ---------------------------------------------------------------------------

/// [`IpRecv`] implementation that yields IP packets generated by smoltcp.
///
/// These packets (TCP SYN, ICMP echo requests, etc.) are ready to be
/// encrypted and sent by GotaTun.
pub struct SmoltcpIpRecv {
    rx: mpsc::Receiver<Vec<u8>>,
    mtu: MtuWatcher,
}

impl IpRecv for SmoltcpIpRecv {
    async fn recv<'a>(
        &'a mut self,
        _pool: &mut PacketBufPool,
    ) -> io::Result<impl Iterator<Item = Packet<Ip>> + Send + 'a> {
        let raw = self
            .rx
            .recv()
            .await
            .ok_or_else(|| io::Error::new(io::ErrorKind::UnexpectedEof, "channel closed"))?;
        let packet = Packet::from_bytes(BytesMut::from(raw.as_slice()));
        let ip_packet = packet
            .try_into_ip()
            .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e.to_string()))?;
        Ok(std::iter::once(ip_packet))
    }

    fn mtu(&self) -> MtuWatcher {
        self.mtu.clone()
    }
}

/// [`IpSend`] implementation that feeds decrypted return traffic into smoltcp.
///
/// Packets sent here (TCP SYN-ACK, ICMP echo replies, etc.) are delivered
/// to the smoltcp stack for processing by TCP/ICMP sockets.
pub struct SmoltcpIpSend {
    tx: mpsc::Sender<Vec<u8>>,
    notify: Arc<Notify>,
}

impl IpSend for SmoltcpIpSend {
    async fn send(&mut self, packet: Packet<Ip>) -> io::Result<()> {
        let raw: Packet<[u8]> = packet.into_bytes();
        let bytes: &[u8] = &*raw;
        self.tx
            .send(bytes.to_vec())
            .await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "channel closed"))?;
        self.notify.notify_one();
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// SmoltcpTcpStream
// ---------------------------------------------------------------------------

/// A TCP stream backed by a smoltcp TCP socket.
///
/// Implements [`AsyncRead`] and [`AsyncWrite`] for use with tonic/gRPC
/// (ephemeral peer exchange) or any other async TCP consumer.
pub struct SmoltcpTcpStream {
    read_rx: mpsc::Receiver<io::Result<Vec<u8>>>,
    write_tx: mpsc::Sender<Vec<u8>>,
    notify: Arc<Notify>,
    read_buf: BytesMut,
    in_flight_write: Option<Pin<Box<dyn std::future::Future<Output = io::Result<usize>> + Send>>>,
}

impl AsyncRead for SmoltcpTcpStream {
    fn poll_read(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &mut ReadBuf<'_>,
    ) -> Poll<io::Result<()>> {
        let this = self.get_mut();

        // Return buffered data first
        if !this.read_buf.is_empty() {
            let n = std::cmp::min(buf.remaining(), this.read_buf.len());
            buf.put_slice(&this.read_buf.split_to(n));
            return Poll::Ready(Ok(()));
        }

        match this.read_rx.poll_recv(cx) {
            Poll::Ready(Some(Ok(data))) => {
                let n = std::cmp::min(buf.remaining(), data.len());
                buf.put_slice(&data[..n]);
                if n < data.len() {
                    this.read_buf.extend_from_slice(&data[n..]);
                }
                Poll::Ready(Ok(()))
            }
            Poll::Ready(Some(Err(e))) => Poll::Ready(Err(e)),
            Poll::Ready(None) => Poll::Ready(Err(io::Error::new(
                io::ErrorKind::BrokenPipe,
                "connection closed",
            ))),
            Poll::Pending => Poll::Pending,
        }
    }
}

impl AsyncWrite for SmoltcpTcpStream {
    fn poll_write(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &[u8],
    ) -> Poll<io::Result<usize>> {
        let this = self.get_mut();

        if let Some(ref mut fut) = this.in_flight_write {
            let result = ready!(fut.as_mut().poll(cx));
            this.in_flight_write = None;
            return Poll::Ready(result);
        }

        let data = buf.to_vec();
        let len = data.len();
        let tx = this.write_tx.clone();
        let notify = this.notify.clone();
        this.in_flight_write = Some(Box::pin(async move {
            tx.send(data)
                .await
                .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "connection closed"))?;
            notify.notify_one();
            Ok(len)
        }));
        cx.waker().wake_by_ref();
        Poll::Pending
    }

    fn poll_flush(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<io::Result<()>> {
        Poll::Ready(Ok(()))
    }

    fn poll_shutdown(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<io::Result<()>> {
        Poll::Ready(Ok(()))
    }
}

// ---------------------------------------------------------------------------
// SmoltcpIcmpSocket
// ---------------------------------------------------------------------------

/// An ICMP socket backed by a smoltcp ICMP socket.
///
/// Send raw ICMP packets (type, code, checksum, id, seq, payload) and
/// receive matching replies.
pub struct SmoltcpIcmpSocket {
    send_tx: mpsc::Sender<(Vec<u8>, IpAddress)>,
    recv_rx: mpsc::Receiver<(Vec<u8>, IpAddress)>,
    notify: Arc<Notify>,
}

impl SmoltcpIcmpSocket {
    /// Send a raw ICMP packet to the given IPv4 destination.
    pub async fn send_to_v4(&self, data: &[u8], dest: Ipv4Addr) -> io::Result<()> {
        self.send_raw(data, IpAddress::Ipv4(dest.into())).await
    }

    /// Send a raw ICMP packet to the given destination.
    pub async fn send_raw(&self, data: &[u8], dest: IpAddress) -> io::Result<()> {
        self.send_tx
            .send((data.to_vec(), dest))
            .await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "socket closed"))?;
        self.notify.notify_one();
        Ok(())
    }

    /// Receive a raw ICMP reply packet. Returns `(data, source_address)`.
    pub async fn recv(&mut self) -> io::Result<(Vec<u8>, IpAddress)> {
        self.recv_rx
            .recv()
            .await
            .ok_or_else(|| io::Error::new(io::ErrorKind::BrokenPipe, "socket closed"))
    }
}

// ---------------------------------------------------------------------------
// Internal types
// ---------------------------------------------------------------------------

enum SocketCmd {
    TcpConnect {
        addr: SocketAddr,
        response: oneshot::Sender<io::Result<SmoltcpTcpStream>>,
    },
    CreateIcmpSocket {
        ident: u16,
        response: oneshot::Sender<io::Result<SmoltcpIcmpSocket>>,
    },
}

struct ActiveTcpSocket {
    socket_handle: SocketHandle,
    read_tx: mpsc::Sender<io::Result<Vec<u8>>>,
    write_rx: mpsc::Receiver<Vec<u8>>,
    write_buf: VecDeque<u8>,
}

struct ActiveIcmpSocket {
    socket_handle: SocketHandle,
    send_rx: mpsc::Receiver<(Vec<u8>, IpAddress)>,
    recv_tx: mpsc::Sender<(Vec<u8>, IpAddress)>,
}

// ---------------------------------------------------------------------------
// Poll loop
// ---------------------------------------------------------------------------

fn smoltcp_now(reference: &StdInstant) -> SmoltcpInstant {
    SmoltcpInstant::from_millis(reference.elapsed().as_millis() as i64)
}

fn to_smoltcp_endpoint(addr: SocketAddr) -> IpEndpoint {
    IpEndpoint {
        addr: match addr {
            SocketAddr::V4(v4) => IpAddress::Ipv4((*v4.ip()).into()),
            SocketAddr::V6(v6) => IpAddress::Ipv6((*v6.ip()).into()),
        },
        port: addr.port(),
    }
}

async fn poll_loop(
    config: SmoltcpNetworkConfig,
    mut from_gotatun_rx: mpsc::Receiver<Vec<u8>>,
    to_gotatun_tx: mpsc::Sender<Vec<u8>>,
    mut cmd_rx: mpsc::Receiver<SocketCmd>,
    notify: Arc<Notify>,
) {
    let reference = StdInstant::now();
    let now = || smoltcp_now(&reference);

    // Set up smoltcp interface
    let mut device = SmoltcpDevice::new(config.mtu);
    let iface_config = IfaceConfig::new(smoltcp::wire::HardwareAddress::Ip);
    let mut iface = Interface::new(iface_config, &mut device, now());

    iface.update_ip_addrs(|addrs| {
        addrs
            .push(IpCidr::new(IpAddress::Ipv4(config.ipv4_addr.into()), 32))
            .expect("enough space for IPv4 address");
        if let Some(v6) = config.ipv6_addr {
            addrs
                .push(IpCidr::new(IpAddress::Ipv6(v6.into()), 128))
                .expect("enough space for IPv6 address");
        }
    });

    // Default routes — the actual routing happens through GotaTun.
    iface
        .routes_mut()
        .add_default_ipv4_route(smoltcp::wire::Ipv4Address::new(0, 0, 0, 1))
        .expect("enough space for default IPv4 route");
    if config.ipv6_addr.is_some() {
        iface
            .routes_mut()
            .add_default_ipv6_route(smoltcp::wire::Ipv6Address::new(0, 0, 0, 0, 0, 0, 0, 1))
            .expect("enough space for default IPv6 route");
    }

    let mut sockets = SocketSet::new(Vec::new());
    let mut active_tcp: Vec<ActiveTcpSocket> = Vec::new();
    let mut active_icmp: Vec<ActiveIcmpSocket> = Vec::new();
    let mut next_local_port: u16 = 49152;

    loop {
        let delay = iface.poll_delay(now(), &sockets);
        let sleep_duration = delay
            .map(|d| std::time::Duration::from_millis(d.total_millis() as u64))
            .unwrap_or(std::time::Duration::from_millis(100));

        tokio::select! {
            biased;

            Some(cmd) = cmd_rx.recv() => {
                handle_cmd(
                    cmd,
                    &mut sockets,
                    &mut iface,
                    &mut device,
                    &notify,
                    &mut active_tcp,
                    &mut active_icmp,
                    &mut next_local_port,
                );
            }

            Some(pkt) = from_gotatun_rx.recv() => {
                device.enqueue_rx(pkt);
            }

            _ = notify.notified() => {}

            _ = tokio::time::sleep(sleep_duration) => {}
        }

        // --- Feed write data from TCP handles into smoltcp sockets ---
        for tcp_sock in active_tcp.iter_mut() {
            // Drain channel into per-socket write buffer
            while let Ok(data) = tcp_sock.write_rx.try_recv() {
                tcp_sock.write_buf.extend(data.iter());
            }

            // Write from buffer into smoltcp socket
            let socket = sockets.get_mut::<tcp::Socket<'_>>(tcp_sock.socket_handle);
            while !tcp_sock.write_buf.is_empty() && socket.can_send() {
                let data = tcp_sock.write_buf.make_contiguous();
                match socket.send_slice(data) {
                    Ok(0) => break,
                    Ok(n) => {
                        tcp_sock.write_buf.drain(..n);
                    }
                    Err(e) => {
                        log::warn!("smoltcp tcp send error: {e}");
                        break;
                    }
                }
            }
        }

        // --- Feed ICMP send requests into smoltcp sockets ---
        for icmp_sock in active_icmp.iter_mut() {
            let socket = sockets.get_mut::<icmp::Socket<'_>>(icmp_sock.socket_handle);
            while socket.can_send() {
                match icmp_sock.send_rx.try_recv() {
                    Ok((data, dest)) => {
                        if let Err(e) = socket.send_slice(&data, dest) {
                            log::warn!("smoltcp icmp send error: {e}");
                            break;
                        }
                    }
                    Err(_) => break,
                }
            }
        }

        // --- Run smoltcp processing ---
        let _ = iface.poll(now(), &mut device, &mut sockets);

        // --- Drain TX from smoltcp device → GotaTun ---
        for pkt in device.drain_tx() {
            if to_gotatun_tx.try_send(pkt).is_err() {
                log::warn!("smoltcp: to_gotatun channel full or closed, dropping packet");
            }
        }

        // --- Read data from established TCP sockets ---
        active_tcp.retain_mut(|tcp_sock| {
            let socket = sockets.get_mut::<tcp::Socket<'_>>(tcp_sock.socket_handle);

            // Push received data to the stream handle
            if socket.can_recv() {
                let queue_len = socket.recv_queue();
                if queue_len > 0 {
                    let mut buf = vec![0u8; queue_len];
                    match socket.recv_slice(&mut buf) {
                        Ok(n) => {
                            buf.truncate(n);
                            if n > 0 {
                                let _ = tcp_sock.read_tx.try_send(Ok(buf));
                            }
                        }
                        Err(e) => {
                            let _ = tcp_sock
                                .read_tx
                                .try_send(Err(io::Error::new(io::ErrorKind::Other, e.to_string())));
                        }
                    }
                }
            }

            // Clean up closed sockets or sockets whose stream was dropped
            let state = socket.state();
            let stream_dropped = tcp_sock.read_tx.is_closed();
            if state == tcp::State::Closed || state == tcp::State::TimeWait || stream_dropped {
                if stream_dropped {
                    socket.close();
                }
                sockets.remove(tcp_sock.socket_handle);
                false
            } else {
                true
            }
        });

        // --- Read data from ICMP sockets ---
        for icmp_sock in active_icmp.iter() {
            let socket = sockets.get_mut::<icmp::Socket<'_>>(icmp_sock.socket_handle);
            while socket.can_recv() {
                match socket.recv() {
                    Ok((data, addr)) => {
                        let _ = icmp_sock.recv_tx.try_send((data.to_vec(), addr));
                    }
                    Err(e) => {
                        log::warn!("smoltcp icmp recv error: {e}");
                        break;
                    }
                }
            }
        }

        // Clean up ICMP sockets whose handles have been dropped
        active_icmp.retain(|s| !s.recv_tx.is_closed());
    }
}

#[allow(clippy::too_many_arguments)]
fn handle_cmd(
    cmd: SocketCmd,
    sockets: &mut SocketSet<'_>,
    iface: &mut Interface,
    _device: &mut SmoltcpDevice,
    notify: &Arc<Notify>,
    active_tcp: &mut Vec<ActiveTcpSocket>,
    active_icmp: &mut Vec<ActiveIcmpSocket>,
    next_local_port: &mut u16,
) {
    match cmd {
        SocketCmd::TcpConnect { addr, response } => {
            let rx_buffer = tcp::SocketBuffer::new(vec![0u8; TCP_BUFFER_SIZE]);
            let tx_buffer = tcp::SocketBuffer::new(vec![0u8; TCP_BUFFER_SIZE]);
            let mut tcp_socket = tcp::Socket::new(rx_buffer, tx_buffer);

            let local_port = *next_local_port;
            *next_local_port = next_local_port.wrapping_add(1).max(49152);

            let local_endpoint = IpListenEndpoint {
                addr: None,
                port: local_port,
            };
            let remote_endpoint = to_smoltcp_endpoint(addr);

            let cx = iface.context();
            if let Err(e) = tcp_socket.connect(cx, remote_endpoint, local_endpoint) {
                let _ = response.send(Err(io::Error::new(
                    io::ErrorKind::Other,
                    format!("smoltcp connect error: {e}"),
                )));
                return;
            }

            let socket_handle = sockets.add(tcp_socket);

            let (read_tx, read_rx) = mpsc::channel(TCP_DATA_CHANNEL_CAPACITY);
            let (write_tx, write_rx) = mpsc::channel(TCP_DATA_CHANNEL_CAPACITY);

            // Return stream immediately. Reads pend until handshake completes
            // and data arrives. Writes buffer in the channel and are flushed
            // once can_send() returns true (after Established state).
            let stream = SmoltcpTcpStream {
                read_rx,
                write_tx,
                notify: notify.clone(),
                read_buf: BytesMut::new(),
                in_flight_write: None,
            };

            active_tcp.push(ActiveTcpSocket {
                socket_handle,
                read_tx,
                write_rx,
                write_buf: VecDeque::new(),
            });

            let _ = response.send(Ok(stream));
        }

        SocketCmd::CreateIcmpSocket { ident, response } => {
            let rx_buffer = icmp::PacketBuffer::new(
                vec![icmp::PacketMetadata::EMPTY; ICMP_METADATA_SLOTS],
                vec![0u8; ICMP_BUFFER_SIZE],
            );
            let tx_buffer = icmp::PacketBuffer::new(
                vec![icmp::PacketMetadata::EMPTY; ICMP_METADATA_SLOTS],
                vec![0u8; ICMP_BUFFER_SIZE],
            );
            let mut icmp_socket = icmp::Socket::new(rx_buffer, tx_buffer);

            if let Err(e) = icmp_socket.bind(icmp::Endpoint::Ident(ident)) {
                let _ = response.send(Err(io::Error::new(
                    io::ErrorKind::Other,
                    format!("smoltcp icmp bind error: {e}"),
                )));
                return;
            }

            let socket_handle = sockets.add(icmp_socket);

            let (send_tx, send_rx) = mpsc::channel(ICMP_CHANNEL_CAPACITY);
            let (recv_tx, recv_rx) = mpsc::channel(ICMP_CHANNEL_CAPACITY);

            active_icmp.push(ActiveIcmpSocket {
                socket_handle,
                send_rx,
                recv_tx,
            });

            let _ = response.send(Ok(SmoltcpIcmpSocket {
                send_tx,
                recv_rx,
                notify: notify.clone(),
            }));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gotatun::packet::PacketBufPool;
    use std::net::Ipv4Addr;

    fn make_network(addr: Ipv4Addr) -> SmoltcpNetwork {
        SmoltcpNetwork::new(SmoltcpNetworkConfig {
            ipv4_addr: addr,
            ipv6_addr: None,
            mtu: 1420,
        })
    }

    /// Test that the SmoltcpNetwork produces valid IP packets when a TCP
    /// connection is initiated. This verifies the end-to-end path from
    /// tcp_connect -> smoltcp -> SmoltcpDevice TX -> IpRecv channel.
    #[tokio::test]
    async fn tcp_connect_produces_syn_packet() {
        let net = make_network(Ipv4Addr::new(10, 0, 0, 1));
        let (handle, mut ip_recv, _ip_send, _guard) = net.into_parts();

        // Start a connection (don't await — no peer to respond)
        let connect_task =
            tokio::spawn(async move { handle.tcp_connect("10.0.0.2:1337".parse().unwrap()).await });

        // Read the SYN packet from IpRecv
        let mut pool = PacketBufPool::new(4);

        let result =
            tokio::time::timeout(std::time::Duration::from_secs(2), ip_recv.recv(&mut pool)).await;

        assert!(result.is_ok(), "Should receive a SYN packet within timeout");
        let iter = result.unwrap().unwrap();
        let packets: Vec<_> = iter.collect();
        assert!(!packets.is_empty(), "Should have at least one packet");

        // Verify it's a valid IPv4 TCP SYN packet
        let first_pkt = packets.into_iter().next().unwrap();
        let raw_pkt = first_pkt.into_bytes();
        let raw: &[u8] = &*raw_pkt;
        assert!(
            raw.len() >= 40,
            "Packet should be at least IPv4 + TCP header"
        );
        assert_eq!(raw[0] >> 4, 4, "Should be IPv4");
        assert_eq!(raw[9], 6, "Should be TCP (protocol 6)");

        let ihl = (raw[0] & 0x0f) as usize * 4;
        let tcp_flags = raw[ihl + 13];
        assert_eq!(tcp_flags & 0x02, 0x02, "SYN flag should be set");

        connect_task.abort();
    }

    /// Test that TCP retransmissions are sent by the smoltcp poll loop even
    /// when the SmoltcpTcpStream futures are not being eagerly polled.
    ///
    /// This is critical: the poll loop must drive the smoltcp stack
    /// independently of whether the user is actively reading/writing the
    /// stream.
    #[tokio::test]
    async fn tcp_retransmissions_without_polling_stream() {
        let net = make_network(Ipv4Addr::new(10, 0, 0, 1));
        let (handle, mut ip_recv, _ip_send, _guard) = net.into_parts();

        // Connect but don't read/write the stream at all
        let _stream =
            tokio::spawn(async move { handle.tcp_connect("10.0.0.2:1337".parse().unwrap()).await });

        // Collect SYN packets from IpRecv over a few seconds.
        // smoltcp should retransmit the SYN because no SYN-ACK arrives.
        let mut pool = PacketBufPool::new(4);
        let mut syn_count = 0u32;

        let deadline = tokio::time::Instant::now() + std::time::Duration::from_secs(5);

        while tokio::time::Instant::now() < deadline {
            let result =
                tokio::time::timeout(std::time::Duration::from_secs(2), ip_recv.recv(&mut pool))
                    .await;

            match result {
                Ok(Ok(iter)) => {
                    for pkt in iter {
                        let raw: &[u8] = &*pkt.into_bytes();
                        if raw.len() >= 40 && raw[9] == 6 {
                            let ihl = (raw[0] & 0x0f) as usize * 4;
                            if raw.len() > ihl + 13 {
                                let tcp_flags = raw[ihl + 13];
                                if tcp_flags & 0x02 != 0 {
                                    syn_count += 1;
                                }
                            }
                        }
                    }
                }
                _ => break,
            }
        }

        assert!(
            syn_count >= 2,
            "Expected at least 2 SYN packets (initial + retransmission), got {syn_count}"
        );
    }

    /// Test that an ICMP echo request can be sent through the SmoltcpNetwork
    /// and received via IpRecv as a valid IP packet.
    #[tokio::test]
    async fn icmp_echo_request_produces_ip_packet() {
        let net = make_network(Ipv4Addr::new(10, 0, 0, 1));
        let (handle, mut ip_recv, _ip_send, _guard) = net.into_parts();

        let icmp_ident: u16 = 0x1234;
        let icmp_socket = handle.icmp_socket(icmp_ident).await.unwrap();

        // Construct an ICMP echo request
        let mut icmp_packet = vec![0u8; 16];
        icmp_packet[0] = 8; // Type: Echo Request
        icmp_packet[1] = 0; // Code: 0
        icmp_packet[4] = (icmp_ident >> 8) as u8;
        icmp_packet[5] = (icmp_ident & 0xff) as u8;
        icmp_packet[6] = 0; // Sequence high
        icmp_packet[7] = 1; // Sequence low
        icmp_packet[8..16].copy_from_slice(&[0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE]);

        // Compute ICMP checksum
        let checksum = internet_checksum(&icmp_packet);
        icmp_packet[2] = (checksum >> 8) as u8;
        icmp_packet[3] = (checksum & 0xff) as u8;

        icmp_socket
            .send_to_v4(&icmp_packet, Ipv4Addr::new(1, 1, 1, 1))
            .await
            .unwrap();

        // Read the IP packet from IpRecv
        let mut pool = PacketBufPool::new(4);

        let result =
            tokio::time::timeout(std::time::Duration::from_secs(2), ip_recv.recv(&mut pool)).await;

        assert!(result.is_ok(), "Should receive ICMP packet within timeout");
        let iter = result.unwrap().unwrap();
        let packets: Vec<_> = iter.collect();
        assert!(!packets.is_empty());

        let first_pkt = packets.into_iter().next().unwrap();
        let raw_pkt = first_pkt.into_bytes();
        let raw: &[u8] = &*raw_pkt;
        assert_eq!(raw[0] >> 4, 4, "Should be IPv4");
        assert_eq!(raw[9], 1, "Should be ICMP (protocol 1)");

        let ihl = (raw[0] & 0x0f) as usize * 4;
        let icmp_data = &raw[ihl..];
        assert_eq!(icmp_data[0], 8, "Should be echo request");
        assert_eq!(
            u16::from_be_bytes([icmp_data[4], icmp_data[5]]),
            icmp_ident,
            "ICMP identifier should match"
        );
    }

    fn internet_checksum(data: &[u8]) -> u16 {
        let mut sum: u32 = 0;
        let mut i = 0;
        while i + 1 < data.len() {
            sum += u16::from_be_bytes([data[i], data[i + 1]]) as u32;
            i += 2;
        }
        if i < data.len() {
            sum += (data[i] as u32) << 8;
        }
        while sum >> 16 != 0 {
            sum = (sum & 0xffff) + (sum >> 16);
        }
        !sum as u16
    }
}
