//! A userspace IP networking stack built on smoltcp, providing TCP and ICMP
//! sockets whose traffic is surfaced as gotatun [`IpSend`]/[`IpRecv`] streams.
//!
//! This is used on iOS where the tunnel process cannot bind sockets to the
//! tunnel device directly. Instead, smoltcp generates raw IP packets that are
//! fed into a GotaTun device via [`IpRecv`], and decrypted return traffic is
//! fed back via [`IpSend`].

mod device;
mod icmp_socket;
mod poll_loop;
mod tcp_stream;

pub use icmp_socket::SmoltcpIcmpSocket;
pub use tcp_stream::SmoltcpTcpStream;

use bytes::BytesMut;
use gotatun::{
    packet::{Ip, Packet, PacketBufPool},
    tun::{IpRecv, IpSend, MtuWatcher},
};
use poll_loop::{SocketCmd, poll_loop};
use std::{
    io,
    net::{Ipv4Addr, Ipv6Addr, SocketAddr},
    sync::Arc,
};
use tokio::{
    sync::{Notify, mpsc, oneshot},
    task::JoinHandle,
};

/// Channel capacity for packets between the smoltcp network and GotaTun.
const PACKET_CHANNEL_CAPACITY: usize = 256;
/// Channel capacity for socket commands.
const CMD_CHANNEL_CAPACITY: usize = 16;

/// Configuration for creating a smoltcp network stack.
pub struct SmoltcpNetworkConfig {
    /// Source IPv4 address for the virtual interface.
    pub ipv4_addr: Ipv4Addr,
    /// Optional source IPv6 address.
    pub ipv6_addr: Option<Ipv6Addr>,
    /// MTU for the virtual interface. Should be `tunnel_mtu - WIREGUARD_HEADER_SIZE`.
    pub mtu: u16,
}

/// Create a new smoltcp-based network stack.
///
/// Spawns a background tokio task that drives the smoltcp interface.
/// Returns the handle, IP recv/send halves, and a guard that aborts
/// the poll loop when dropped.
pub fn smoltcp_network(
    config: SmoltcpNetworkConfig,
) -> (
    SmoltcpHandle,
    SmoltcpIpRecv,
    SmoltcpIpSend,
    SmoltcpNetworkGuard,
) {
    let (to_gotatun_tx, to_gotatun_rx) = mpsc::channel(PACKET_CHANNEL_CAPACITY);
    let (from_gotatun_tx, from_gotatun_rx) = mpsc::channel(PACKET_CHANNEL_CAPACITY);
    let (cmd_tx, cmd_rx) = mpsc::channel(CMD_CHANNEL_CAPACITY);
    let notify = Arc::new(Notify::new());

    let mtu_watcher = MtuWatcher::new(config.mtu);

    let ip_recv = SmoltcpIpRecv {
        rx: to_gotatun_rx,
        mtu: mtu_watcher,
    };

    let ip_send = SmoltcpIpSend {
        tx: from_gotatun_tx,
        notify: notify.clone(),
    };

    let handle = SmoltcpHandle {
        cmd_tx,
        notify: notify.clone(),
    };

    let poll_task = tokio::spawn(poll_loop(
        config,
        from_gotatun_rx,
        to_gotatun_tx,
        cmd_rx,
        notify,
    ));

    (
        handle,
        ip_recv,
        ip_send,
        SmoltcpNetworkGuard { poll_task },
    )
}

/// Guard that aborts the poll loop task when dropped.
pub struct SmoltcpNetworkGuard {
    poll_task: JoinHandle<()>,
}

impl Drop for SmoltcpNetworkGuard {
    fn drop(&mut self) {
        self.poll_task.abort();
    }
}

/// A cloneable handle for creating sockets on the smoltcp network stack.
#[derive(Clone)]
pub struct SmoltcpHandle {
    cmd_tx: mpsc::Sender<SocketCmd>,
    notify: Arc<Notify>,
}

impl SmoltcpHandle {
    /// Open a TCP connection to the given address through the smoltcp stack.
    ///
    /// The returned stream may be used immediately. Reads will pend until the
    /// TCP handshake completes and data arrives. Writes are buffered and
    /// flushed once the connection is established.
    pub async fn tcp_connect(&self, addr: SocketAddr) -> io::Result<SmoltcpTcpStream> {
        let (tx, rx) = oneshot::channel();
        self.cmd_tx
            .send(SocketCmd::TcpConnect { addr, response: tx })
            .await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "poll loop closed"))?;
        self.notify.notify_one();
        rx.await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "poll loop dropped"))?
    }

    /// Create an ICMP socket bound to the given identifier.
    ///
    /// Only ICMP echo replies matching this identifier will be delivered.
    pub async fn icmp_socket(&self, ident: u16) -> io::Result<SmoltcpIcmpSocket> {
        let (tx, rx) = oneshot::channel();
        self.cmd_tx
            .send(SocketCmd::CreateIcmpSocket {
                ident,
                response: tx,
            })
            .await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "poll loop closed"))?;
        self.notify.notify_one();
        rx.await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "poll loop dropped"))?
    }
}

/// [`IpRecv`] implementation that yields IP packets generated by smoltcp.
///
/// These packets (TCP SYN, ICMP echo requests, etc.) are ready to be
/// encrypted and sent by GotaTun.
pub struct SmoltcpIpRecv {
    rx: mpsc::Receiver<Vec<u8>>,
    mtu: MtuWatcher,
}

impl IpRecv for SmoltcpIpRecv {
    async fn recv<'a>(
        &'a mut self,
        _pool: &mut PacketBufPool,
    ) -> io::Result<impl Iterator<Item = Packet<Ip>> + Send + 'a> {
        let raw = self
            .rx
            .recv()
            .await
            .ok_or_else(|| io::Error::new(io::ErrorKind::UnexpectedEof, "channel closed"))?;
        let packet = Packet::from_bytes(BytesMut::from(raw.as_slice()));
        let ip_packet = packet
            .try_into_ip()
            .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e.to_string()))?;
        Ok(std::iter::once(ip_packet))
    }

    fn mtu(&self) -> MtuWatcher {
        self.mtu.clone()
    }
}

/// [`IpSend`] implementation that feeds decrypted return traffic into smoltcp.
///
/// Packets sent here (TCP SYN-ACK, ICMP echo replies, etc.) are delivered
/// to the smoltcp stack for processing by TCP/ICMP sockets.
pub struct SmoltcpIpSend {
    tx: mpsc::Sender<Vec<u8>>,
    notify: Arc<Notify>,
}

impl IpSend for SmoltcpIpSend {
    async fn send(&mut self, packet: Packet<Ip>) -> io::Result<()> {
        let raw: Packet<[u8]> = packet.into_bytes();
        let bytes: &[u8] = &*raw;
        self.tx
            .send(bytes.to_vec())
            .await
            .map_err(|_| io::Error::new(io::ErrorKind::BrokenPipe, "channel closed"))?;
        self.notify.notify_one();
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gotatun::packet::PacketBufPool;
    use std::net::Ipv4Addr;

    fn make_network(
        addr: Ipv4Addr,
    ) -> (
        SmoltcpHandle,
        SmoltcpIpRecv,
        SmoltcpIpSend,
        SmoltcpNetworkGuard,
    ) {
        smoltcp_network(SmoltcpNetworkConfig {
            ipv4_addr: addr,
            ipv6_addr: None,
            mtu: 1420,
        })
    }

    /// Test that the SmoltcpNetwork produces valid IP packets when a TCP
    /// connection is initiated. This verifies the end-to-end path from
    /// tcp_connect -> smoltcp -> SmoltcpDevice TX -> IpRecv channel.
    #[tokio::test]
    async fn tcp_connect_produces_syn_packet() {
        let (handle, mut ip_recv, _ip_send, _guard) = make_network(Ipv4Addr::new(10, 0, 0, 1));

        // Start a connection (don't await — no peer to respond)
        let connect_task =
            tokio::spawn(async move { handle.tcp_connect("10.0.0.2:1337".parse().unwrap()).await });

        // Read the SYN packet from IpRecv
        let mut pool = PacketBufPool::new(4);

        let result =
            tokio::time::timeout(std::time::Duration::from_secs(2), ip_recv.recv(&mut pool)).await;

        assert!(result.is_ok(), "Should receive a SYN packet within timeout");
        let iter = result.unwrap().unwrap();
        let packets: Vec<_> = iter.collect();
        assert!(!packets.is_empty(), "Should have at least one packet");

        // Verify it's a valid IPv4 TCP SYN packet
        let first_pkt = packets.into_iter().next().unwrap();
        let raw_pkt = first_pkt.into_bytes();
        let raw: &[u8] = &*raw_pkt;
        assert!(
            raw.len() >= 40,
            "Packet should be at least IPv4 + TCP header"
        );
        assert_eq!(raw[0] >> 4, 4, "Should be IPv4");
        assert_eq!(raw[9], 6, "Should be TCP (protocol 6)");

        let ihl = (raw[0] & 0x0f) as usize * 4;
        let tcp_flags = raw[ihl + 13];
        assert_eq!(tcp_flags & 0x02, 0x02, "SYN flag should be set");

        connect_task.abort();
    }

    /// Test that an ICMP echo request can be sent through the SmoltcpNetwork
    /// and received via IpRecv as a valid IP packet.
    #[tokio::test]
    async fn icmp_echo_request_produces_ip_packet() {
        let (handle, mut ip_recv, _ip_send, _guard) = make_network(Ipv4Addr::new(10, 0, 0, 1));

        let icmp_ident: u16 = 0x1234;
        let icmp_socket = handle.icmp_socket(icmp_ident).await.unwrap();

        // Construct an ICMP echo request
        let mut icmp_packet = vec![0u8; 16];
        icmp_packet[0] = 8; // Type: Echo Request
        icmp_packet[1] = 0; // Code: 0
        icmp_packet[4] = (icmp_ident >> 8) as u8;
        icmp_packet[5] = (icmp_ident & 0xff) as u8;
        icmp_packet[6] = 0; // Sequence high
        icmp_packet[7] = 1; // Sequence low
        icmp_packet[8..16].copy_from_slice(&[0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE]);

        // Compute ICMP checksum
        let checksum = internet_checksum(&icmp_packet);
        icmp_packet[2] = (checksum >> 8) as u8;
        icmp_packet[3] = (checksum & 0xff) as u8;

        icmp_socket
            .send_to_v4(&icmp_packet, Ipv4Addr::new(1, 1, 1, 1))
            .await
            .unwrap();

        // Read the IP packet from IpRecv
        let mut pool = PacketBufPool::new(4);

        let result =
            tokio::time::timeout(std::time::Duration::from_secs(2), ip_recv.recv(&mut pool)).await;

        assert!(result.is_ok(), "Should receive ICMP packet within timeout");
        let iter = result.unwrap().unwrap();
        let packets: Vec<_> = iter.collect();
        assert!(!packets.is_empty());

        let first_pkt = packets.into_iter().next().unwrap();
        let raw_pkt = first_pkt.into_bytes();
        let raw: &[u8] = &*raw_pkt;
        assert_eq!(raw[0] >> 4, 4, "Should be IPv4");
        assert_eq!(raw[9], 1, "Should be ICMP (protocol 1)");

        let ihl = (raw[0] & 0x0f) as usize * 4;
        let icmp_data = &raw[ihl..];
        assert_eq!(icmp_data[0], 8, "Should be echo request");
        assert_eq!(
            u16::from_be_bytes([icmp_data[4], icmp_data[5]]),
            icmp_ident,
            "ICMP identifier should match"
        );
    }

    fn internet_checksum(data: &[u8]) -> u16 {
        let mut sum: u32 = 0;
        let mut i = 0;
        while i + 1 < data.len() {
            sum += u16::from_be_bytes([data[i], data[i + 1]]) as u32;
            i += 2;
        }
        if i < data.len() {
            sum += (data[i] as u32) << 8;
        }
        while sum >> 16 != 0 {
            sum = (sum & 0xffff) + (sum >> 16);
        }
        !sum as u16
    }
}
