import SwiftUI

extension Image {
    static var mullvadIconClose: some View {
        Image("IconClose")
            .resizable()
            .frame(width: 25, height: 25)
    }

    static let mullvadIconAlert = Image("IconAlert")
    static let mullvadIconSpinner = Image("IconSpinner")
    static let mullvadIconSuccess = Image("IconSuccess")
    static let mullvadIconFail = Image("IconFail")
    static let mullvadIconSearch = Image("IconSearch")
    static let mullvadIconCross = Image("IconCross")
    static let mullvadIconChevron = Image("IconChevron")
    static let mullvadIconAdd = Image("IconAdd")
    static let mullvadIconEdit = Image("IconEdit")
    static let mullvadIconTick = Image("IconTick")
    static let mullvadIconStateOnline = Image("IconStateOnline")
    static let mullvadIconStateOffline = Image("IconStateOffline")
    static let mullvadIconStateIssue = Image("IconStateIssue")
    static let mullvadIconInternet = Image("IconInternet")
    static let mullvadServer = Image("IconServer")
    static let mullvadSmartphone = Image("IconSmartphone")
    static let mullvadLocation = Image("IconLocation")
    static let mullvadIconError = Image("IconError")
    static let mullvadIconInfo = Image("IconInfo")
    static let mullvadIconDelete = Image("IconDelete")
    static let mullvadIconMultihopAlways = Image("IconMultihopAlways")
    static let mullvadIconMultihopNever = Image("IconMultihopNever")
    static let mullvadIconMultihopWhenNeeded = Image("IconMultihopWhenNeeded")
    static let mullvadIconEnableRecents = Image("IconEnableRecents")
    static let mullvadIconDisableRecents = Image("IconDisableRecents")
    static let mullvadIconFilter = Image("IconFilter")
    static let mullvadIconFilterDisabled = Image("IconFilterDisabled")
    static let mullvadIconFilterCutout = Image("IconFilterCutout")
    static let mullvadIconFilterCutoutDisabled = Image("IconFilterCutoutDisabled")
    static let mullvadIconReload = Image("IconReload")
    static let mullvadAutomaticMultihopBanner = Image("AutomaticMultihopBanner")
    static let mullvadUniqueFilterBanner = Image("UniqueFilterBanner")
}
