#!/usr/bin/env bash

# This script creates and pushes a signed release tag. This should be run after `1-prepare-release`.

set -eu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

REPO_ROOT=../../../
PRODUCT_VERSION_PATH=$REPO_ROOT/dist-assets/desktop-product-version.txt
PRODUCT_VERSION=$(cat $PRODUCT_VERSION_PATH)

source $REPO_ROOT/scripts/utils/print-and-run
source $REPO_ROOT/scripts/utils/log

function push_tag {
    product_version=$(echo -n "$PRODUCT_VERSION")
    echo "Tagging current git commit with release tag $product_version..."
    print_and_run git tag -s "$product_version" -m "$product_version"
    git push
    print_and_run git push origin "$product_version"
    log_success "\nTag pushed!"
}

git verify-commit HEAD
push_tag
