#!/usr/bin/env bash

set -eu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

./update-and-publish-metadata "$@"
./publish-repositories "$1" "$2"

echo "Waiting 2m before checking repository package versions..."
sleep 2m
./verify-package-versions --production "$1"
