#!/usr/bin/env bash

set -eu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

REPO_ROOT=../../../
ENVIRONMENT="$1"
PRODUCT_VERSION="$2"

source $REPO_ROOT/scripts/utils/log

print_versions_args=( "$ENVIRONMENT" )

if [[ "$PRODUCT_VERSION" == *-beta* ]]; then
  print_versions_args+=( --beta )
fi

deb_version_output=$(./print-package-versions --deb "${print_versions_args[@]}")
deb_version=$(echo "$deb_version_output" | grep mullvad-vpn | awk '{print $2}' | sed 's/~/-/')

if [[ "$deb_version" != "$PRODUCT_VERSION" ]]; then
  log_error "Incorrect deb version in repository ($deb_version)"
  echo "$deb_version_output"
  exit 1
fi

rpm_version_output=$(./print-package-versions --rpm "${print_versions_args[@]}")
rpm_version=$(echo "$rpm_version_output" | grep mullvad-vpn | awk '{print $2}' | sed 's/~/-/')

if [[ "$rpm_version" != "$PRODUCT_VERSION-1" ]]; then
  log_error "Incorrect rpm version in repository ($rpm_version)"
  echo "$rpm_version_output"
  exit 1
fi
