---
name: Android - Pre-release check
on:
  pull_request:
    paths:
      - .github/workflows/android-pre-release-check.yml
      - 'android/src/main/play/release-notes/en-US/default.txt'
      - 'android/CHANGELOG.md'

permissions: {}

jobs:
  check-changelog:
    runs-on: android-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Run pre-release checks
        run: |
          version=$(./building/container-run.sh linux "cargo run -q --bin mullvad-version versionCode")
          android/scripts/check-changelog.sh version
