name: Mullvad VPN daemon CI
on:
    # Build whenever a file that affects a Rust crate is changed by a push
    push:
        paths-ignore:
            - .github/*.md
            - .github/workflows/android*.yml
            - .github/workflows/rustfmt.yml
            - android/**
            - audits/**
            - ci/**
            - dist-assets/**
            - docs/**
            - graphics/**
            - gui/**
            - ios/**
            - mullvad-jni/**
            - scripts/**
            - '**/*.md'
            - '.*ignore'
            - .editorconfig
            - .gitattributes
            - .travis.yml
            - Dockerfile
            - build.sh
            - build-apk.sh
            - integration-tests.sh
            - prepare-release.sh
            - rustfmt.toml
            - update-api-address.sh
            - update-relays.sh
            - version-metadata.sh
    # Build if requested manually from the Actions tab
    workflow_dispatch:
jobs:
    build-linux:
        strategy:
            matrix:
                rust: [stable, beta, nightly]

        runs-on: ubuntu-latest
        steps:
            # Checkout repository
            - uses: actions/checkout@v2

            # Checkout binaries submodule
            - run: |
                git submodule update --init --depth=1 dist-assets/binaries

            # Install Rust
            - uses: ATiltedTree/setup-rust@v1.0.4
              with:
                  rust-version: ${{ matrix.rust }}

            # Install Go
            - uses: actions/setup-go@v2.1.3
              with:
                  go-version: 1.16

            # Install build dependencies
            - run: sudo apt-get install libdbus-1-dev

            # Build and test crates
            - env:
                RUSTFLAGS: --deny warnings
              run: |
                ./wireguard/build-wireguard-go.sh
                source env.sh
                time cargo build --locked --verbose
                time cargo test --locked --verbose

    build-macos:
        runs-on: macos-latest
        steps:
            # Checkout repository
            - uses: actions/checkout@v2

            # Install Rust
            - uses: ATiltedTree/setup-rust@v1.0.4
              with:
                  rust-version: stable

            # Install Go
            - uses: actions/setup-go@v2.1.3
              with:
                  go-version: 1.16

            # Build and test crates
            - env:
                RUSTFLAGS: --deny warnings
              run: |
                ./wireguard/build-wireguard-go.sh
                source env.sh
                time cargo build --locked --verbose
                time cargo test --locked --verbose

    build-windows:
        runs-on: windows-latest
        steps:
            # Checkout repository
            - uses: actions/checkout@v2

            # Checkout submodules
            - run: git submodule update --init --depth=1

            # Install Rust
            - uses: ATiltedTree/setup-rust@v1.0.4
              with:
                  rust-version: stable

            # Install Go
            - uses: actions/setup-go@v2.1.3
              with:
                  go-version: 1.16

            # Install msbuild
            - uses: microsoft/setup-msbuild@v1.0.2
              with:
                  vs-version: 16

            # Build and test crates
            - env:
                RUSTFLAGS: --deny warnings
              shell: bash
              run: |
                ./wireguard/build-wireguard-go.sh
                time ./build_windows_modules.sh --dev-build
                source env.sh
                time cargo build --locked --verbose
                time cargo test --locked --verbose
