---
name: iOS create screenshots
on:
  push:
    tags:
      - ios/*
  pull_request:
    paths:
      - ios/Gemfile
      - ios/Gemfile.lock
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: {}

jobs:
  test:
    name: Take screenshots
    runs-on: macos-26-xlarge
    env:
      SOURCE_PACKAGES_PATH: .spm
      TEST_ACCOUNT: ${{ secrets.IOS_TEST_ACCOUNT_NUMBER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup project
        uses: ./.github/actions/ios/setup-project-toolchain

      - name: Copy relay list
        run: cp MullvadREST/Assets/relays-test-data.json MullvadREST/Assets/relays.json
        working-directory: ios

      - name: Add test account to config
        run: |
          sed -i "" \
            "/HAS_TIME_ACCOUNT_NUMBER =/ s#= .*#= 1234123412341234#" \
            UITests.xcconfig
        working-directory: ios/Configurations

      - name: Bundle
        run: bundle install
        working-directory: ios

      - name: Create screenshots
        run: bundle exec fastlane snapshot --cloned_source_packages_path "$SOURCE_PACKAGES_PATH"
        working-directory: ios

      - name: Determine artifact name
        id: artifact-name
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.ref_name }}
          HEAD_REF: ${{ github.head_ref }}
          SHA: ${{ github.sha }}
        run: |
          if [ "$REF_TYPE" = "tag" ]; then
            name="$REF_NAME"
          else
            name="${HEAD_REF:-$REF_NAME}-$(date -u +%Y%m%d)-${SHA:0:7}"
          fi
          stripped_name=$(printf '%s' "$name" | \
                                  sed -e 's/[^[:alnum:]_-]/-/g' \
                                    -e 's/--*/-/g' \
                                    -e 's/^-//' \
                                    -e 's/-$//')

          # Artifact names may not contain path separators or other reserved characters.
          echo "name=ios-screenshots-${stripped_name}" >> "$GITHUB_OUTPUT"

      - name: Upload screenshot artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: ios/Screenshots
