# Run `cargo fmt --check` on the `test` workspace
---
name: DES Testframework - Check formatting
on:
  pull_request:
    paths:
      - 'test/**/*.rs'
      - .github/workflows/rustfmt-test.yml
      - rustfmt.toml
  workflow_dispatch:

permissions: {}

jobs:
  check-formatting-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install Rust components
        shell: bash
        run: rustup component add rustfmt

      - name: Check formatting
        working-directory: test
        run: |-
          rustfmt --version
          cargo fmt -- --check
