name: Verify lockfile signatures
on:
    pull_request:
        paths:
            - .github/workflows/verify-lockfile-signatures.yml
            - Cargo.lock
            - gui/package-lock.json
    workflow_dispatch:
jobs:
    verify-signatures:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Verify signatures
              run: |
                commits=${{ github.event.pull_request.commits }}
                if [[ -n "$commits" ]]; then
                    # Prepare enough depth for diffs with master
                    git fetch --depth="$(( commits + 1 ))"
                fi
                ci/verify-lockfile-signature.sh origin/master
