package net.mullvad.mullvadvpn.lib.ui.theme.color

internal object ColorDarkTokens {
    val Background = PaletteTokens.DarkBlue
    val Error = PaletteTokens.Red
    val ErrorContainer = PaletteTokens.Red
    val InverseOnSurface = PaletteTokens.Black // Currently not in use
    val InversePrimary = PaletteTokens.Black // Currently not in use
    val InverseSurface = PaletteTokens.MullvadWhite
    val OnBackground = PaletteTokens.MullvadWhite
    val OnError = PaletteTokens.MullvadWhite
    val OnErrorContainer = PaletteTokens.MullvadWhite
    val OnPrimary = PaletteTokens.MullvadWhite
    val OnPrimaryContainer = PaletteTokens.MullvadWhite
    val OnPrimaryFixed = PaletteTokens.Black // Currently not in use
    val OnPrimaryFixedVariant = PaletteTokens.Black // Currently not in use
    val OnSecondary = PaletteTokens.MullvadWhite
    val OnSecondaryContainer = OpacityTokens.WhiteOnDarkBlue60
    val OnSecondaryFixed = PaletteTokens.Black // Currently not in use
    val OnSecondaryFixedVariant = PaletteTokens.Black // Currently not in use
    val OnSurface = PaletteTokens.MullvadWhite
    val OnSurfaceVariant = OpacityTokens.WhiteOnDarkBlue60
    val OnTertiary = PaletteTokens.MullvadWhite
    val OnTertiaryContainer = OpacityTokens.WhiteOnDarkBlue60
    val OnTertiaryFixed = PaletteTokens.Black // Currently not in use
    val OnTertiaryFixedVariant = PaletteTokens.Black // Currently not in use
    val Outline = PaletteTokens.Blue
    val OutlineVariant = PaletteTokens.DarkBlue
    val Primary = PaletteTokens.Blue
    val PrimaryContainer = PaletteTokens.Blue
    val PrimaryFixed = PaletteTokens.Black // Currently not in use
    val PrimaryFixedDim = PaletteTokens.Black // Currently not in use
    val Scrim = PaletteTokens.Black
    val Secondary = PaletteTokens.DarkerBlue50
    val SecondaryContainer = PaletteTokens.DarkerBlue50
    val SecondaryFixed = PaletteTokens.Black // Currently not in use
    val SecondaryFixedDim = PaletteTokens.Black // Currently not in use
    val Surface = PaletteTokens.DarkBlue
    val SurfaceBright = PaletteTokens.Blue
    val SurfaceContainerHighest = PrimaryContainer
    val SurfaceContainerHigh = OpacityTokens.BlueOnDarkBlue60
    val SurfaceContainer = OpacityTokens.BlueOnDarkBlue40
    val SurfaceContainerLow = OpacityTokens.BlueOnDarkBlue20
    val SurfaceContainerLowest = OpacityTokens.BlueOnDarkBlue10
    val SurfaceDim = PaletteTokens.Black // Currently not in use
    val SurfaceTint = PaletteTokens.Black // Currently not in use
    val SurfaceVariant = PaletteTokens.DarkerBlue50
    val Tertiary = PaletteTokens.DarkerBlue10
    val TertiaryContainer = PaletteTokens.DarkerBlue10
    val TertiaryFixed = PaletteTokens.Black // Currently not in use
    val TertiaryFixedDim = PaletteTokens.Black // Currently not in use
}
