package net.mullvad.mullvadvpn.lib.ui.theme.color

// This is experimental and currently not used
internal object ColorLightTokens {
    val Background = PaletteTokens.Black
    val Error = PaletteTokens.Black
    val ErrorContainer = PaletteTokens.Black
    val InverseOnSurface = PaletteTokens.Black
    val InversePrimary = PaletteTokens.Black
    val InverseSurface = PaletteTokens.Black
    val OnBackground = PaletteTokens.Black
    val OnError = PaletteTokens.Black
    val OnErrorContainer = PaletteTokens.Black
    val OnPrimary = PaletteTokens.Black
    val OnPrimaryContainer = PaletteTokens.Black
    val OnPrimaryFixed = PaletteTokens.Black
    val OnPrimaryFixedVariant = PaletteTokens.Black
    val OnSecondary = PaletteTokens.Black
    val OnSecondaryContainer = PaletteTokens.Black
    val OnSecondaryFixed = PaletteTokens.Black
    val OnSecondaryFixedVariant = PaletteTokens.Black
    val OnSurface = PaletteTokens.Black
    val OnSurfaceVariant = PaletteTokens.Black
    val OnTertiary = PaletteTokens.Black
    val OnTertiaryContainer = PaletteTokens.Black
    val OnTertiaryFixed = PaletteTokens.Black
    val OnTertiaryFixedVariant = PaletteTokens.Black
    val Outline = PaletteTokens.Black
    val OutlineVariant = PaletteTokens.Black
    val Primary = PaletteTokens.Black
    val PrimaryContainer = PaletteTokens.Black
    val PrimaryFixed = PaletteTokens.Black
    val PrimaryFixedDim = PaletteTokens.Black
    val Scrim = PaletteTokens.Black
    val Secondary = PaletteTokens.Black
    val SecondaryContainer = PaletteTokens.Black
    val SecondaryFixed = PaletteTokens.Black
    val SecondaryFixedDim = PaletteTokens.Black
    val Surface = PaletteTokens.Black
    val SurfaceBright = PaletteTokens.Black
    val SurfaceContainer = PaletteTokens.Black
    val SurfaceContainerHighest = PaletteTokens.Black
    val SurfaceContainerHigh = PaletteTokens.Black
    val SurfaceContainerLow = PaletteTokens.Black
    val SurfaceContainerLowest = PaletteTokens.Black
    val SurfaceDim = PaletteTokens.Black
    val SurfaceTint = PaletteTokens.Black
    val SurfaceVariant = PaletteTokens.Black
    val Tertiary = PaletteTokens.Black
    val TertiaryContainer = PaletteTokens.Black
    val TertiaryFixed = PaletteTokens.Black
    val TertiaryFixedDim = PaletteTokens.Black
}
